### ISSUE TITLE
xml-files inpection ignores external DTD

### ISSUE THREAD

**Issue by ppisar** [rpminspect/rpminspect#110]
Here <http://fedora-build-checks.apps.ci.centos.org/job/fedora-rpminspect/3778/artifact/package-tests/logs/rpminspect.json>:

~~~~
   "xml-files": [
     {
       "result": "VERIFY",
       "waiver authorization": "Anyone",
       "message": "File \/usr\/share\/help\/C\/gscan2pdf\/documentation.html has become malformed XML on noarch",
       "screendump": "Entity 'ouml' not defined\n",
       "remedy": "Correct the reported errors in the XML document"
     }
~~~~

The file is fine. The ouml entity is defined in "-//W3C//DTD XHTML 1.0 Strict//EN" DTD. Compare:

~~~~
$ xmllint --noout /tmp/out2 
/tmp/out2:546: parser error : Entity 'deg' not defined
<h3 id="Rotate-90-clockwise">Rotate 90&deg; clockwise</h3>
                                           ^
/tmp/out2:550: parser error : Entity 'deg' not defined
<h3 id="Rotate-180">Rotate 180&deg;</h3>
                                   ^
/tmp/out2:552: parser error : Entity 'deg' not defined
<h3 id="Rotate-90-anticlockwise">Rotate 90&deg; anticlockwise</h3>
                                               ^
/tmp/out2:709: parser error : Entity 'ouml' not defined
<li><p>Bj&ouml;rn Lindqvist for the gtkimageview widget</p>
               ^
$ xmllint --noout --loaddtd /tmp/out2 
~~~~

rpminspect should respect XML DTD declaration or disable the test.

**Comment by dcantrell** [comment]
You're right.  I'm looking in to this now.

**Comment by dcantrell** [comment]
OK, progress so far.  Since SVG files are XML but lack a DTD line (sometimes?), I decided to validate them using librsvg2.  If it can't open the file, we'll report that as an invalid SVG file.

For the other XML files I am seeing two problems:
- It's picking HTML files in doc subdirectories as XML to validate.  Not sure if this is necessary or not.
- It's not loading the DTD for XML files.  This is what I am actively working on because it's my incorrect use of libxml2 it appears.

More to come.

**Comment by ppisar** [comment]
I think that recent libxml2 does not load external DTDs by default for
security reasons.

**Comment by dcantrell** [comment]
Yeah, that's what I'm finding out.  I'm making progress here.  I think for SVG files I might just do a syntax validation rather than trying to load it using librsvg2.  I don't do that for any other image files.

**Comment by dcantrell** [comment]
Oh I see.  Even with XML_PARSE_NONET, I need the DTD files available locally for libxml2.  Those are provided by xhtml1-dtds and html401-dtds packages.  I will add those as Requires to the spec file for rpminspect.  Still looking at SVG syntax validation.

**Comment by dcantrell** [comment]
OK, I think I have a patch set that is much nicer.  Here's what I do now:

- If a found XML file ends with ".svg" assume it's SVG and skip it.  I'm not sure we want to care about using libxml to validate these or even try to load them in to memory in rpminspect.  If we should do that, I think it should be a separate inspection.
- For XML files, first try to validate by loading the specified DTD.  Be sure to XML_PARSE_NONET to prevent network downloads.  This requires have the dtd packages installed locally, so I added that as Requires to librpminspect.
- If the DTD validation fails and the error code returned is XML_DTD_NO_DTD, then try it again without trying to load a DTD.  This is basically just syntax validation.
- Also silence libxml2's default behavior of sending parse errors to stderr.  I collect those a different way so that's just redundant.

Return from that.  Here's what I get now:

```
$ rpminspect -T xml gscan2pdf-2.6.5-1.fc31
xml-files:
----------
Result: OK
```

**Comment by ppisar** [comment]
Awesome.
