### ISSUE TITLE
rpminspect fails to specify how to obtain debuginfo when invoked on Rust executable

### ISSUE THREAD

**Issue by bgurney-rh** [rpminspect/rpminspect#1110]
**Describe the bug**
For some reason, the annocheck test seems to be failing to pass the "--debug-dir" option, to locate the debug info.

**To Reproduce**
(rpminspect command string from CI for https://bodhi.fedoraproject.org/updates/FEDORA-2023-94eab844b3)

/usr/bin/rpminspect -c /usr/share/rpminspect/fedora.yaml --workdir /var/ARTIFACTS/work-rpminspectne9n6w38/rpminspect/discover/default-0/tests/workdir/ --format=json --output=/var/ARTIFACTS/work-rpminspectne9n6w38/rpminspect/execute/data/rpminspect/data/result.json --verbose --release=fc39 --profile=rawhide stratisd-3.5.1-2.fc39 98124882

Result of one of the annocheck commands:
```
Command: annocheck --ignore-unknown --verbose --profile=rawhide /usr/bin/stratis-min
Exit Code: 1
    compared with the output of:
Command: annocheck --ignore-unknown --verbose --profile=rawhide /usr/bin/stratis-min
Exit Code: 1
```

**Expected behavior**
```
Details:
Command: annocheck --ignore-unknown --verbose --profile=rawhide /usr/bin/stratis-min
Exit Code: 1
    compared with the output of:
Command: annocheck --ignore-unknown --verbose --profile=rawhide --debug-dir=/var/tmp/rpminspect/stratisd-3.5.1.DM1PpE/root/after/x86_64 /usr/bin/stratis-min
Exit Code: 0
```

**Environment:**
Fedora upstream Testing-Farm, running on the update for stratisd-3.5.1-3.fc39 (https://bodhi.fedoraproject.org/updates/FEDORA-2023-94eab844b3)

**Comment by dcantrell** [comment]
OK, I figured out the problem and have patched it.  Just waiting on tests before posting the PR.

The issue is that nothing in our package building infrastructure can agree on what 32-bit x86 architectures should be called.  Koji spells it "i386", rpmbuild spells it "i686" because of what we actually build for in that target, and then find-debuginfo spells it "i386" again.  rpminspect was unable to find the debuginfo file because of this inconsistency.

What I did was rewrite the arch handling in rpminspect to treat them as fnmatch(3) patterns.  Right now that's only applicable to 32-bit x86, which is fine.  This also has the side effect of letting you specify "-a i686" on the rpminspect command line and not being told i686 is an unsupported architecture.  The annocheck inspection will now do fnmatch(3) matching to select the debuginfo path.

I verified this works for the i686 package and continued working for the other architectures.  PR coming momentarily.
