### ISSUE TITLE
Don't comlain about LicenseRef-ISO-8879

### ISSUE THREAD

**Issue by omajid** [rpminspect/rpminspect#1237]
**Describe the bug**

rpminspect complains about LicenseRef-ISO-8879. For example, at https://fedora.softwarefactory-project.io/rpminspect-report/?url=https://centos.softwarefactory-project.io/logs//1/1/62b8d2f820aed21d4a6230c16148bc3b4b1c2087/check/rpm-rpminspect/0bfe000/result.json

However, Fedora allows this license under certain conditions: https://gitlab.com/fedora/legal/fedora-license-data/-/blob/main/data/LicenseRef-ISO-8879.toml

Can rpminspect allow this license?

**To Reproduce**
```
rpminspect-centos -Dv -k -t VERIFY --profile=centos-stream-9-devel -w /data/rpminspect -a x86_64,noarch,src -o /home/fedora/zuul-output/logs/result.json -F json
 /data/rpminspect/dotnet8.0-8.0.100~preview.7-0.1.el9~bootstrap
```

You can get the rpms from https://centos.softwarefactory-project.io/logs/1/1/62b8d2f820aed21d4a6230c16148bc3b4b1c2087/check/mock-build/010c063/repo/dotnet8.0-8.0.100~preview.7-0.1.el9~bootstrap/

**Expected behavior**
rpminspect doesn't fail on this license.

**Environment:**
 - OS and architecture: Zuul, see https://centos.softwarefactory-project.io/zuul/t/centos/build/0bfe000c2bcc42a4a6431863460fad59

**Comment by dcantrell** [comment]
If the license is approved, it should be in the fedora-license-data project.  That project then needs to do a new package build so it's available at runtime for rpminspect.  The approved licenses come from the data provided by that package.

**Comment by dcantrell** [comment]
The data file in fedora-license-data probably needs revision.  I recommend opening a new ticket in that project to get legal to review it.  The status is "not-allowed" which means it will show up as not approved in the license db and rpminspect will treat it as such.  If it has an exception under which it is allowed, it needs to be in some allowed category otherwise rpminspect won't know about it at all.

**Comment by richardfontana** [comment]
The design of the license approval system is such that some licenses are by default not allowed but in certain defined fact situations, often highly specific to one package, they are permitted. I would assume this is going to be beyond the capacity of a tool like rpminspect to detect and presumably some sort of human review is necessary to ascertain that the usage scenario is met in a given case. I don't see any way around this other than to have a more rigid system in which a not-allowed license is *always* not allowed with no possibility for any exceptions.

**Comment by omajid** [comment]
What are the next steps here? rpminspect continues to complain about my package which uses this license in the allowed-exception-context.

**Comment by richardfontana** [comment]
@omajid I am not familiar with how rpminspect is used. In Fedora, if rpminspect fails dotnet because the License: lists something classified as not-allowed, what happens? Are you blocked from having dotnet in Fedora, or are you the one blocking yourself? 

Couldn't it be part of a process that is not 100% automated? So if rpminspect fails dotnet, you go to an authorized human who verifies that dotnet fits the established usage exception, for example. 

In theory, I'm not totally opposed to the idea of a package-specific `LicenseRef-Fedora-` identifier but this could imply, for example, creation of potentially hundreds of `CC0-1.0` LicenseRefs. I think it is important to signal somehow that inclusion of a not-allowed license is problematic even where it fits a documented usage exception.  

I'm just not clear on why this is a problem in general. (In this case it might be because of this specific license - would have to re-review it.) 

cc: @jlovejoy

**Comment by omajid** [comment]
rpminspect is used the release pipeline for Fedora and RHEL for releasing new packages as well any updates to existing packages.

Currently, every package update with such a license is flagged as an issue. For example, here's a package update that fixes a security issue in .NET 7 for Fedora with this license tag: https://bodhi.fedoraproject.org/updates/FEDORA-2023-7a8c827dda. rpminspect ran against it and flagged that something failed: 
![image](https://github.com/rpminspect/rpminspect/assets/174451/0c91bce6-b849-4c8c-aa20-bc9a724d8464).

Following the failed test messages takes me to the [rpminspect log](https://artifacts.dev.testing-farm.io/f4b26122-06ee-455d-8c19-fea673bdb3bb/) which shows that it's because of this license tag. 

As a maintainer, I have to dig into what test failed, and why. Alternatively, I can ignore it, and risk missing an actual issue in my package.

On Fedora, there's no hard blocker for the update, I can release the update and completely ignore the rpminspect findings.

Other distributions, such as RHEL, treat it a bit more strongly. On RHEL, rpminspect failures block the release. Thankfully, it's not a hard blocker, but it requires manually reviewing the error messages and for devs/qe to sign off every time rpminspect fails. This also pauses an otherwise fully automated process and introduces additional delay in a release.

If this was manual work that happened just once, or even once every year, it wouldn't be too bad. But rpminspect runs on every .NET update, and we have multiple of those every month.

(As a side note, ignoring the rpminspect error is what I have done till now. This is a bad idea, because, looking through the rpminspect logs on Fedora, I just found *another* license that rpminspect is complaining about and this other license issue is a real issue that we can/should fix.)

I wonder if it would be an option to add this license tag to the per-package `rpminspect.yaml` file (with a link to the exception/approval), and have rpminspect ignore/waive this failure like it dos for many other things?

**Comment by omajid** [comment]
Can we please re-open this?

If fixing the license list isn't an option, can we add support for allowing licenses via the rpminspect.yaml file?
