### ISSUE TITLE
Java doesn't need to be multilib compatible

### ISSUE THREAD

**Issue by cipherboy** [rpminspect/rpminspect#126]
Per [FESCo ticket](https://pagure.io/fesco/issue/961), Java packages don't need to be multilib compatible. I believe this should extend at least to `javadoc` and `.jar` files, but I don't know how far we should take it.

Some discussion points include:

 - Should this be configurable? Path based exceptions?
 - What about packages with native libraries, e.g., JSS? Do the corresponding `.so` files need to be multilib clean, even though they're expected to only be used from Java and not directly as libraries?

**Comment by dcantrell** [comment]
Are Java packages noarch or arch-specific?  My first thought is this could be handled by MIME type per file since Java is unique enough for that.  I'd rather do that than maintain a lot of path exceptions since packaging policy might change that later on.

**Comment by cipherboy** [comment]
Depends on the Java package:

 - https://koji.fedoraproject.org/koji/buildinfo?buildID=1474343 (arch-specific)
 - https://koji.fedoraproject.org/koji/buildinfo?buildID=1433837 (noarch)

:-)

**Comment by cipherboy** [comment]
Just bumping this:

You can take a look at an internal `/run/472849/18/` if you're interested for more useless multiarch differences. Other than building a specific subpackage (javadoc?) as noarch (is that even possible?), I'm not sure there's anything you can do when the JDK tool spits out different i686/x86_64 content for documentation:

> Multilib difference for usr/share/javadoc/jss-4.8.0/org/mozilla/jss/netscape/security/x509/Extensions.html on x86_64 vs i686:
>     --- /usr/share/javadoc/jss-4.8.0/org/mozilla/jss/netscape/security/x509/Extensions.html on x86_64	2020-11-11 15:48:23.920216039 +0000
>     +++ /usr/share/javadoc/jss-4.8.0/org/mozilla/jss/netscape/security/x509/Extensions.html on i686	2020-11-11 16:03:19.285376873 +0000
>     @@ -288,7 +288,7 @@ implements <a href="../../../../../../or
>      
>      </a>
>      <h3>Methods inherited from class&nbsp;java.lang.Object</h3>
>     -<code>finalize, getClass, notify, notifyAll, wait, wait, wait</code></li>
>     +<code>finalize, getClass, notify, notifyAll, toString, wait, wait, wait</code></li>
>      </ul>
>      <ul class="blockList">
>      <li class="blockList"><a name="methods.inherited.from.class.org.mozilla.jss.netscape.security.x509.CertAttrSet">

**Comment by dcantrell** [comment]
I'm not longer sure what's actionable here.  Since this bug was opened, rpminspect has gained global file path ignores and per-inspection file path ignores (using wildcard globbing syntax too).  The most recent comment looks like an error with peering when comparing builds.  rpminspect should not have peered the i686 package with the x86_64 package, but I can't tell for sure if that's what happened here.

Nothing has come up in the years since this bug was opened, so I'm inclined to think most of the annoyances were sorted out through additional rpminspect functionality/bug fixing.

Lastly, rpminspect doesn't do anything multilib-specific.  Its ancestor did, but none of that was retained for rpminspect.  It peers and compares RPMs from a build across whatever architectures appear.  But there's nothing that says "oh, if you have x86_64, then you also need i686" in rpminspect.

If I have missed something here, let me know.  I know it's taken forever for me to get to this one, but it's not the longest bug to remain open.  :)

**Comment by cipherboy** [comment]
Makes sense, thank you David!!
