### ISSUE TITLE
Composed messages can not be properly translated

### ISSUE THREAD

**Issue by goeranu** [rpminspect/rpminspect#1268]
After [line 554 of inspect_patches.c](https://github.com/rpminspect/rpminspect/blob/550fc49bb834c56b341e7a81c834b2342e055be0/lib/inspect_patches.c#L554) there are three print statements that compose a message that optionally adds an "s" to a word if there are more than one line/file, and also might insert "as many as".

Composing messages in that way makes them impossible to translate properly. "S" is only a plural suffix in some languages obviously. Furthermore, many languages have other plural distinctions than simple singular/plural like English. In that case, Swedish which I'm translating into has the same pattern as English, but many languages distinguish more cases.

The correct way to handle this is to use the `ngettext` function, where you give the English singular and plural and also the number, and then the function can select between serveral messages different for each target language.

**Comment by dcantrell** [comment]
Thank you!  I am definitely not an expert on the translation functions, but I wanted to set things up in the code so that strings could be translated.  I will prepare a patch as you describe for inspect_patches.c and let me know if that looks correct to you.  If it does, I can merge it and get the translation template updated.  There are probably many other examples like this in the code, so please do point them out so I can fix them.

**Comment by goeranu** [comment]
I'm sure you can google it yourself, but in case you would like here is a [pointer](https://www.gnu.org/software/gettext/manual/html_node/Plural-forms.html) to the documentation around `ngettext`.

**Comment by dcantrell** [comment]
Yep, I found it.

**Comment by dcantrell** [comment]
Does this pull request look correct to fix the translation problem with these strings?

**Comment by goeranu** [comment]
Yes, it looks good to me!
