### ISSUE TITLE
get_changelog: Assertion `hdr != NULL' failed.

### ISSUE THREAD

**Issue by ukulekek** [rpminspect/rpminspect#127]
Hello!
We are getting next error:
```
$ rpminspect -v servicemesh-cni-1.1.0-3.el8 servicemesh-cni-1.1.0-3.el8arches
...
rpminspect: ../lib/inspect_changelog.c:46: get_changelog: Assertion `hdr != NULL' failed.
Aborted (core dumped)
```
More reproducers:
```
rpminspect -v libreoffice-6.0.6.1-19.el8 libreoffice-6.3.5.2-6.el8
rpminspect -v cockpit-195.5-2.el7 cockpit-195.8-1.el7_9
```
We have next packages:
```
rpminspect-0.11-0.1.202004082101git.fc31.x86_64
rpminspect-data-redhat-0.9-0.1.202003262048git.fc31.noarch
librpminspect-0.11-0.1.202004082101git.fc31.x86_64
```

**Comment by dcantrell** [comment]
Thanks for the report, working on this one now.

**Comment by dcantrell** [comment]
Should not be segfaulting now, but I am not sure if the behavior is correct.  The two builds specified have mismatched architecture availability.  What output are you expecting from the changelog inspection for these two builds?

**Comment by dcantrell** [comment]
It looks like the only thing that changed is the disttag.  The version and release are the same.  And the spec files are the same.  I think this should return OK since the builds are the same except the disttag.  What do you think?

**Comment by ukulekek** [comment]
Agree, I think OK is suitable here.

**Comment by dcantrell** [comment]
Alright, I will work on that because right now I've got it returning BAD and reporting there is no new changelog entry.  The release test is actually saying it's different because of the dist tag.  So let me work on that a bit.

**Comment by dcantrell** [comment]
OK, I have a fix for this now.  I've added a set of functions to librpminspect that retrieve the Release value from the spec file of a build then trims the macros trailing the release value.  I do this because librpm will give me the expanded Release value when I ask for the RPMTAG_RELEASE value from the header.  So in the first example you gave me, I get "3.el8" and "3.el8arches" are the Release values.  But the only thing different is the dist tag.  Macros are a problem here.

What I do now is read the Release: line from the spec file and trim everything from the first macro and to the end of the line.  This may not be foolproof, but it is within the packaging policy for Fedora and RHEL.  In the first example, I now get:

"servicemesh-cni-1.1.0-3"
"servicemesh-cni-1.1.0-3"

As the NVR.  When the changelog inspection detects no new entry, it checks these NVRs to see if they match.  If they do, the inspection returns OK.  Otherwise it returns BAD indicating there is no new entry.

```
$ rpminspect -T changelog -F json servicemesh-cni-1.1.0-3.el8 servicemesh-cni-1.1.0-3.el8arches
{
   "changelog": [
     {
       "result": "OK",
       "waiver authorization": "Not Waivable"
     }
   ]
 }
```
