### ISSUE TITLE
rpminspect warns about net_driver builtin

### ISSUE THREAD

**Issue by keszybz** [rpminspect/rpminspect#1294]
New systemd build:
https://artifacts.dev.testing-farm.io/0f49e367-3397-4fd8-8118-ce5bac36e2fd/

/usr/lib/udev/rules.d/50-udev-default.rules:29 Unknown builtin command: net_driver
/usr/lib/udev/rules.d/50-udev-default.rules: udev rules check failed.

This was added in systemd 255.

**Comment by dcantrell** [comment]
The udevrules inspection uses udevadm.  Since systemd provides that, you may want to just disable the udevrules inspection for the package since it will be running the udevadm that is available for installation and not the command that is available in the package.

I could modify things so if the package is providing 'udevadm', use that instead of the one on the system but that feels like it might be too confusing to debug later on.  My recommendation would be to disable the udevrules inspection in rpminspect.yaml for systemd.  I assume you have some sort of CI in place to run udevadm verify on the rules files in systemd, so with something like that running before making releases I feel that would give the same level of sanity checking as the udevrules inspection in rpminspect.

**Comment by keszybz** [comment]
Oh, I wasn't aware that it's using`udevadm`. Yeah, I think then we should disable this check in systemd builds. Any pointer to docs how to do this best?

**Comment by dcantrell** [comment]
In your `rpminspect.yaml` file, make sure you have an inspections block like this:

```
inspections:
    # this inspection uses `udevadm` which comes from this package
    # disable so we do not check udev rules with a possibly outdated version
    # of the command
    udevrules: off
```

If you already have an inspections section, just add the udevrules line.

**Comment by keszybz** [comment]
Thanks! I added it now.
