### ISSUE TITLE
Possible false-positive: "Existing subpackage kernel-debug is now missing on s390x"

### ISSUE THREAD

**Issue by jankaluza** [rpminspect/rpminspect#1310]
**Describe the bug**
This is related to OSCI-5970. The rpminspect says that there is a missing kernel-debug subpakage on s390s, but in the build system, we see the package present even for s390x.

**To Reproduce**

/usr/bin/rpminspect -c /usr/share/rpminspect/redhat.yaml --workdir /tmp --format=json --output=result.json --verbose --release=el9 kernel-5.14.0-362.13.1.el9_3 kernel-5.14.0-362.14.1.el9_3

**Expected behavior**

The kernel-debug is not reported as missing if it's there.

**Environment:**
 - OS and architecture

**Comment by dcantrell** [comment]
Unable to reproduce this locally.  The details I found via the OSCI issue showed you're running rpminspect 1.13.  The latest builds in Copr are now at 2.0, though I don't know that this was a recently fixed problem.  I ran everything locally and the lostpayload inspection passed, unlike what you're seeing in gating.

A possible issue is the amount of disk space the worker has.  In the diagnostics section, rpminspect reports it needs 19G to store the builds and then 70G to unpack everything.

If you can reproduce this again, please let me know.  But without a usable reproducer, the problem is going to be elsewhere.

**Comment by dcantrell** [comment]
@jankaluza ^^

**Comment by jankaluza** [comment]
@dcantrell , Michal is going to update to latest rpminspect today, so let's see if this fixes the issue or not.

**Comment by jankaluza** [comment]
@dcantrell , this can be closed. It seems update to latest rpminspect fixed this issue.
