### ISSUE TITLE
Value of type INT supplied where string type was expected.

### ISSUE THREAD

**Issue by ukulekek** [rpminspect/rpminspect#137]
Hello!
I'm trying to run rpminspect for modules, but in every case I get the next error:
```
$ rpminspect -v  -T modularity python38-3.8-8020020200309184510.bbc63041 python38-3.8-8030020200507162918.4190259b
XML-RPC Fault: Value of type INT supplied where string type was expected. (-501)
Aborted (core dumped)
```
Is it expected? Should I specify module different way?

My environment:
* fedora 31
* rpminspect-0.12-0.1.202005081927git.fc31.x86_64
* librpminspect-0.12-0.1.202005081927git.fc31.x86_64
* rpminspect-data-redhat-0.9-0.1.202005051747git.fc31.noarch

**Comment by dcantrell** [comment]
This is not expected.  It looks like the Koji API changed again.

**Comment by dcantrell** [comment]
Yeah, Koji now calls 'epoch' a string where it used to call it an integer.  Fixing.

**Comment by dcantrell** [comment]
Well it's worse than just the XML-RPC change.  The entire structure of how modules can be downloaded seems to have changed.  I am working on resolving this.

**Comment by dcantrell** [comment]
I have fixed the XML-RPC issues and am fixing up the download loop for SRPMs that contain binary RPMs that alter the RPMTAG_NAME value.  The problem with this when downloading modules and not regular builds is that the member RPMs of the module are stored on the Koji download server based on the RPMTAG_NAME value of the SRPM that built it and not based on the name of the module.  I should have this fixed up tomorrow.

**Comment by dcantrell** [comment]
OK, final conclusion here:

1) module_build_service_id changed from a string to an int in the Koji XML-RPC API.  That's bad, had to change that.  Would like it if Koji's XML-RPC API was stable.
2) Download URLs for module component RPMs need to use each build's NVR data for download URL path construction rather than the module NVR data.  When I call getLatestBuilds, I collect all the information returned to build correct paths.

Testing now, will push when I finish that up.

**Comment by dcantrell** [comment]
And it's fixed.  I imagine there may be more module problems to resolve, but I have at least fixed this one for now.  :)
