### ISSUE TITLE
[RFE] changelog inspection could ignore addition/deletion of whitespace

### ISSUE THREAD

**Issue by ckelleyRH** [rpminspect/rpminspect#1410]
**Is your feature request related to a problem? Please describe.**
Sometimes maintainers tidy up spec files by adding/removing whitespace in the changelog - perhaps this is a response to running `fedpkg lint` or similar which issues warnings about spec file hygiene. Anyway, this causes `changelog` to fail because the changelog history was "rewritten" but it hasn't been materially altered. 

**Describe the solution you'd like**
`changelog` ignores lines that were simply added/removed whitespace.

**Describe alternatives you've considered**
The alternative is to just accept it, but this involves individual maintainers recognising the problem and/or support orgs diagnosing it which takes time to do.

**Additional context**
N/A

**Comment by dcantrell** [comment]
Can you give me an example set of Koji builds where this happens?  I think this is a reasonable enhancement, I just need an example set of builds as test input.

**Comment by ckelleyRH** [comment]
> Can you give me an example set of Koji builds where this happens? I think this is a reasonable enhancement, I just need an example set of builds as test input.

Sure! The failed inspection in CentOS Stream CI log has expired, but I have access to the RHEL equivalent if you want it. The inspection was between these builds: [nvme-cli-2.6-5.el9](https://kojihub.stream.centos.org/koji/buildinfo?buildID=59610) -> [nvme-cli-2.9.1-3.el9](https://kojihub.stream.centos.org/koji/buildinfo?buildID=62649).

...and I diffed the spec files as part of my analysis, so here is the result:
```
diff 2.6.5 2.9.1
1d0
< 
2a2,13
> * Wed June 19 2024 Maurizio Lombardi <mlombard@redhat.com> - 2.9.1-3
> - Fix RHEL-36139
> 
> * Tue May 07 2024 Tomas Bzatek <tbzatek@redhat.com> - 2.9.1-2
> - Install custom nvmf-connect-nbft.sh NetworkManager hook (RHEL-18912)
> 
> * Tue May 07 2024 Maurizio Lombardi <mlombard@redhat.com> - 2.9.1-1
> - Update to version 2.9.1
> 
> * Wed Apr 03 2024 Maurizio Lombardi <mlombard@redhat.com> - 2.8-1
> - Update to version 2.8
> 
28a40
> 
48a61
> 
68a82
> 
151a166
> 
171a187
> 
173a190,191
> 
> 
```

**Comment by dcantrell** [comment]
OK, I was able to reproduce this locally and with the latest upstream development version.  It is true that you see a VERIFY result which causes gating to fail since it classifies anything at the VERIFY level or higher as a failure.

Looking in to this further, it appears this inspection originated back when RH had stricter requirements around what goes in the %changelog for each build and the purposes was to ensure the maintainer was doing that.  Sadly, the check was to simply see that it _grew_ not that it really contained the required information (which I actually don't think was documented anywhere).  Mostly this was about bot controls that we used to put in %changelog entries.

With things like auto changelogs and changelog housekeeping, I don't think there's value in this inspection being so strict.  I will continue to let it report changes but everything will be at the INFO level.  If that is somehow wrong, I am sure I will hear about it.

Personally I think the %changelog in RPMs has outlived its usefulness.  Back in the time period of all upstream source coming to you as a tarball, I think there was value.  But now we can build to RPM directly from git repos and we have much better change information both in the version control log but also the files in the repo itself.  Some people still prefer the %changelog, which is fine, so I'm sure they will stay for a while.  If it were up to me we would do away with it and instead have an optional external file for package maintainers to document any changes to the package in an informal structure.  If that file existed (and noted in the spec file with something like ChangesSource: so that rpmbuild knows to include it in SRPM), rpmbuild would place it in %docdir.  But that's just my idea.  For projects where the maintainer is also the upstream for a package, I don't see a reason for %changelog or this hypothetical file existing.

Anyways, patch posting soon.
