### ISSUE TITLE
rpminspect doesn't recognize explicit Requires

### ISSUE THREAD

**Issue by vashirov** [rpminspect/rpminspect#1427]
**Describe the bug**
rpminspect reports issues with 389-ds-base spec file:

> Subpackage 389-ds-base-bdb on aarch64 carries 'Requires: libback-ldbm.so()(64bit)' which comes from subpackage 389-ds-base but does not carry an explicit package version requirement. Please add 'Requires: 389-ds-base = %{version}-%{release}' to the spec file to avoid the need to test interoperability between various combinations of old and new subpackages.

But the subpackage has Requires, although it uses macro:
https://gitlab.com/redhat/centos-stream/rpms/389-ds-base/-/blob/c10s/389-ds-base.spec?ref_type=heads#L566-567

```
Requires:         %{name} = %{version}-%{release}
Requires:         %{name}-libs = %{version}-%{release}
```

**Comment by dcantrell** [comment]
I worked on reproducing this one locally yesterday.  It took a while to track down, but the problem is not in rpminspect.  It is a packaging problem with 389-ds-base.

When rpminspect is looking for those explicit Requires, it does not look at the spec file.  It is looking at the built RPMs and what is in the headers.  In the case of the 389-ds-base-bdb subpackage, it was missing both explicit Requires that you noted in the spec file.  Other subpackages had explicit Requires, so it was initially confusing.  Then I saw what was going on.

The bdb subpackage block in the spec was incorrectly written.  The Requires and Provides lines need to come before the description.  Right now it looks like this:

```
%if %{with bundle_libdb}
%package          bdb
Summary:          Berkeley Database backend for 389 Directory Server
%description      bdb
Berkeley Database backend for 389 Directory Server
Warning! This backend is deprecated in favor of lmdb and its support
may be removed in future versions.

Requires:         %{name} = %{version}-%{release}
Requires:         %{name}-libs = %{version}-%{release}
# Berkeley DB database libdb was marked as deprecated since F40:                
# https://fedoraproject.org/wiki/Changes/389_Directory_Server_3.0.0             
# because libdb was marked as deprecated since F33                              
# https://fedoraproject.org/wiki/Changes/Libdb_deprecated                       
Provides:         deprecated()
%endif
```

This is a problem for rpmbuild because it is still reading lines for the description when it encounters the Requires and Provides lines.  So those never end up in the subpackage RPM header which causes the rpminspect error.

The block in the spec file should look like this:

```
%if %{with bundle_libdb}
%package          bdb
Summary:          Berkeley Database backend for 389 Directory Server

Requires:         %{name} = %{version}-%{release}
Requires:         %{name}-libs = %{version}-%{release}
# Berkeley DB database libdb was marked as deprecated since F40:                
# https://fedoraproject.org/wiki/Changes/389_Directory_Server_3.0.0             
# because libdb was marked as deprecated since F33                              
# https://fedoraproject.org/wiki/Changes/Libdb_deprecated                       
Provides:         deprecated()

%description      bdb
Berkeley Database backend for 389 Directory Server
Warning! This backend is deprecated in favor of lmdb and its support
may be removed in future versions.
%endif
```

**Comment by vashirov** [comment]
Thank you for tracking this down!
