### ISSUE TITLE
Please inspect for ABI breaking issues, including level 4 packages.

### ISSUE THREAD

**Issue by jimbair** [rpminspect/rpminspect#172]
When a developer explicitly enable ABI checker for a level 4 package, they want to be informed about failures.

References:
BZ#1334414

**Comment by dcantrell** [comment]
I think this is successfully bitrotted.  The ABI inspection has compatibility levels are implemented in rpminspect using the rpmdiff config file syntax, but supporting an arbitrary number of levels.  rpmdiff never had level 4 defined in the config files either.

Closing this since there's nothing actionable on it for now.
