### ISSUE TITLE
Support patches using git am

### ISSUE THREAD

**Issue by jimbair** [rpminspect/rpminspect#177]
parted uses 'git am' to add patches, which we should support:

%prep
%setup -q
gpg2 --import %{SOURCE2} %{SOURCE3}
gpg2 --verify %{SOURCE1} %{SOURCE0}
git init
git config user.email "parted-owner@fedoraproject.org"
git config user.name "Fedora Ninjas"
git add .
git commit -a -q -m "%{version} baseline."
[ -n "%{patches}" ] && git am %{patches}
iconv -f ISO-8859-1 -t UTF8 AUTHORS > tmp; touch -r AUTHORS tmp; mv tmp AUTHORS
git commit -a -m "run iconv"

Reference: BZ#1704448

**Comment by dcantrell** [comment]
rpminspect does not check to see that each Patch defined in a spec file has a corresponding %patch macro in the %prep section.  For starters, it's possible to include patches that are not used in the build.  Either conditionally or just commented out but otherwise included in the SRPM.  Second, spec files now have %autopatch and %autosetup which eliminates the need for pairing up each Patch to a %patch macro.

The only thing that would make sense is a %patch macro that references an undefined patch.  But that would be caught by rpmbuild anyway, so rpminspect doesn't need to do that.
