### ISSUE TITLE
Properly handle rebases and validate build URLs

### ISSUE THREAD

**Issue by jimbair** [rpminspect/rpminspect#179]
rpminspect should handle rebases consistently across all steps and inspections; see references for more context. It's important we catch rebases correctly to avoid any surprises in a build; i.e. shipping unexpected code.

One example; we should have a list of acceptable paths for build URLs to be coming from. As always, there's a lot more context in the below BZs.

References: 
BZ#1726177
BZ#1726178
BZ#1726179
BZ#1726180

**Comment by dcantrell** [comment]
I think this one can be closed out now because I went through and added the is_rebase() function and concept of detecting a rebase in librpminspect.  Inspections now use the result of this boolean function to set their reporting levels.  Rebases typically reset reporting severity to INFO for rebase comparisons, but keep it at VERIFY for non-rebase comparisons (that is, maintenance updates).

Closing this one out.  Any further issues on this topic can be handled as ordinary bug reports.
