### ISSUE TITLE
rpminspect should mention the RAM and DISK requirements

### ISSUE THREAD

**Issue by thrix** [rpminspect/rpminspect#255]
I believe it is worth to document the RAM and DISK space requirements of rpminspect, ideally some maxium values for the largest packages. Seems we are hitting limits of 8GB RAM for firefox.

Also it would make sense to test the ram usage in tests, just in case there would be some regression in memory handling.

**Comment by dcantrell** [comment]
I can explain that you will need enough space and RAM to handle the builds you want to compare, but I have no way of knowing what a maximum would be.  Firefox is a good example as is the kernel in terms of large builds that take a lot of space when unpacked.

I also don't understand what test you would want for this.  It has nothing to do with rpminspect and everything to do with the inputs you give it.  Right now I have GitHub Actions that run for rpminspect that perform comparisons on the following packages:  zsh, kernel, python3, mutt, emacs, tmux, elfutils.  It ensures the program runs to completion and does not crash.  If you have other suggestions for the list, let me know.

**Comment by thrix** [comment]
> I can explain that you will need enough space and RAM to handle the builds you want to compare, but I have no way of knowing what a maximum would be. Firefox is a good example as is the kernel in terms of large builds that take a lot of space when unpacked.

I see, yeah, ok, I guess this is something we need to find out then. We were just looking for some guidance

> I also don't understand what test you would want for this. It has nothing to do with rpminspect and everything to do with the inputs you give it. Right now I have GitHub Actions that run for rpminspect that perform comparisons on the following packages: zsh, kernel, python3, mutt, emacs, tmux, elfutils. It ensures the program runs to completion and does not crash. If you have other suggestions for the list, let me know.

The idea behind the test was to measure memory and disk usage for each test on the same package versin, to rule out any possibility of regressions in the usage of those resources. And it was mainly an idea, currently it is hard to tell if these change in time or not, and how much.

**Comment by dcantrell** [comment]
One thing I can do is add a CI job in the project to just report resource usage for a subset of builds.  I think kernel would be a good check and firefox and maybe libreoffice.  Occassionally there are some other surprises too in terms of largest builds, so any ideas here would be helpful.  Instead of CI, this could just be static data that I generate for each release and put in the README file or something like that.

I'd use something like sysstat to collect memory and CPU stats and then run rpminspect with -k to compute total disk space used for the job.  I could then prepare some graphs and charts and put that in the README.

Thoughts?

**Comment by dcantrell** [comment]
Nothing actionable here.  If you have an idea of how best recommended runtime requirements can be expressed, feel free to reopen the issue.
