### ISSUE TITLE
rpminspect does not honor `-w` option to set workdir

### ISSUE THREAD

**Issue by thrix** [rpminspect/rpminspect#256]
We set in CI workdir to a relative path to the current directory, but it does not seem to be honored:

We pass option `-w tmphILGPJ/artifacts`, but at least the downloaded artifacts are still default `/var/tmp/rpminspect`.

**Comment by thrix** [comment]
Seems more just like artifacts:

```
bash-5.0$ ls -al /var/tmp/rpminspect/ && du -sh /var/tmp/rpminspect/
total 132
drwxr-xr-x. 3 jenkins jenkins  4096 Nov 11 09:50 .
drwxrwxrwt. 1 root    root     4096 Nov 11 09:43 ..
-rw-------. 1 jenkins jenkins 26205 Nov 11 09:50 changelog.0jTwOS
-rw-------. 1 jenkins jenkins 26366 Nov 11 09:50 changelog.4K6wuT
-rw-------. 1 jenkins jenkins 26366 Nov 11 09:50 changelog.bzRJWS
-rw-------. 1 jenkins jenkins 26205 Nov 11 09:50 changelog.poeqVQ
drwx------. 5 jenkins jenkins  4096 Nov 11 09:50 ovn2.13-20.09.0.LAm2QT
1.3G    /var/tmp/rpminspect/
```

**Comment by happz** [comment]
The problem we face: we use `-w` to point `rpminspect` to a very special mount where it has enough space, much more than `/var/tmp` can offer, and while 1.3 GB may seem quite low, `-w` being ignored bites us painfully when we start dealing with packages like Firefox where 40+ GB disk space usage is nothing uncommon.

**Comment by morucci** [comment]
Hi, I got the same issue on our CI

```[root@29978afad116 ~]# rpminspect-fedora -v -w /tmp/test -f python-gear-0.15.1-5.fc34
Downloading https://kojipkgs.fedoraproject.org/packages/python-gear/0.15.1/5.fc34/src/python-gear-0.15.1-5.fc34.src.rpm...
Downloading https://kojipkgs.fedoraproject.org/packages/python-gear/0.15.1/5.fc34/noarch/python3-gear-0.15.1-5.fc34.noarch.rpm...

Keeping working directory: /root/python-gear-0.15.1-5.fc34
[root@29978afad116 ~]# ls
anaconda-ks.cfg  anaconda-post-nochroot.log  anaconda-post.log  original-ks.cfg  python-gear-0.15.1-5.fc34

```

**Comment by thrix** [comment]
@dcantrell hi, could we get this fixed soon please? we need to apply workarounds due this in CI. And we are not very happy about it.

**Comment by dcantrell** [comment]
Looks like with the -f option, I am always writing to the current working directory.  Should be easy enough to fix.

**Comment by dcantrell** [comment]
OK, got this fixed up.  I'm running the test suite right now.  There were two errors.  The first was in the if statement that picks up relative directory path specifications, such as "-w ../my_builds" and then resolves them.  The second error was with the use of realpath(3).  I will explain.

My test expression matching relative directory paths was just wrong.  It was missing another pair of parentheses.  Things like /tmp/test were matched by this test.  I added the parens and it stopped matching incorrect paths.

The second part was the main issue.  I use realpath(3) to canonicalize paths, but that only works if the specified directory exists.  The gather_builds() function will ultimately make the directory it needs to write to, so realpath(3) should only be used if the specified directory exists.  Otherwise take the directory specified and let it fall through to gather_builds() as the user expects.

That is what I have done and I am now able to specify "/tmp/test" when using -f and it works fine.

Thanks for the report!

**Comment by dcantrell** [comment]
Merged
