### ISSUE TITLE
RFE: Allow to specify architectures

### ISSUE THREAD

**Issue by hroncok** [rpminspect/rpminspect#27]
For quick debugging and for integration with Fedora CI pipeline, it would be nice if I could say for example: "I only care about x86_64,noarch,src", to prevent downloading and unpacking extra unwanted packages (~320 MiB for python3).

**Comment by dcantrell** [comment]
This is a really good idea.  Where should I get a list of valid architectures?  Since rpminspect is tied to rpm and that universe, should I ask rpm or otherwise look at what it calls an architecture?  Should I allow any string and just match every package it iterates through and skip the ones that do not match?  That would probably be expensive because it would need to download all packages anyway and that can be avoided.

**Comment by hroncok** [comment]
How do you ask Koji for the download links? Maybe it has some kind of options for this already?

**Comment by dcantrell** [comment]
Found it.  I can call getAllArches() on the Koji hub and get a list of supported architecture names.  I can then validate the command line input from the user and abort if the user gives me an invalid architecture name.  Working on the patch.

**Comment by dcantrell** [comment]
Done.  See the commits linked in this issue.  Basically you do this:

rpminspect -a x86_64,s390x,src

To restrict it to those architectures.  Works for downloaded builds and local builds, however the architecture list is validated against what the Koji hub supports.
