### ISSUE TITLE
Split test filter into --testwith and --testwithout

### ISSUE THREAD

**Issue by jimbair** [rpminspect/rpminspect#28]
Instead of having users specify a "\!test" syntax to exclude tests, let's try something like --testwith and --testwithout (or whatever sounds good). The switches should be mutually exclusive, meaning you can tell rpminspect to exclude 1 or more tests and run the remaining tests, or you explicitly say which tests you want run.

**Comment by dcantrell** [comment]
This makes more sense.  I am using -T now, which I would like to use to specify the tests to perform.  What about -W for tests to exclude?  But I'm also not sure about this wording.  Thoughts?

**Comment by jimbair** [comment]
That sounds good to me; the only other thought I had was -T for tests and -E for --excludes; though I don't have any dogs in this particular fight. =)

**Comment by dcantrell** [comment]
OK, -T and -E it is.  Working on the patch.

**Comment by dcantrell** [comment]
The purpose of this change is to avoid the \!testname syntax to exclude a test from an rpminspect run.  By default, all tests that apply will run.  There are now the -T and -E options:

If you specify -T, then all tests are disabled by default and only the tests you specify on this option are enabled.  You can pass "-T ALL" to enable all tests, but that is the default behavior.

If you specify -E, then all tests are enabled by default and only the tests you specify on this option are disabled.  You can pass "-E ALL" to disable all tests, but that is sort of pointless because rpminspect ends
up doing nothing.

The options cannot be used together.  The man page and README have been updated.
