### ISSUE TITLE
Catch macro expansion issues with missing (Build)Requires

### ISSUE THREAD

**Issue by cipherboy** [rpminspect/rpminspect#307]
Recently I was rebuilding Tomcat and ran into this strange error:

```
error: File must begin with "/": %{_unitdir}/tomcat.service
```

If not for `brp-mangle-shebangs` failing the build, I would've missed it entirely and the resulting package would've installed a bunch of files to paths with `%{_unitdir}` in them. That would've been... less than ideal :-)

This error is caused by a missing BuildRequires dependency on either `systemd` or more precisely, `systemd-rpm-macros`.

Could we get a `rpminspect` pass to check for potentially unexpanded macros in filesystem paths?

**Comment by dcantrell** [comment]
This is a good idea.  Macro expansion hits a lot of packages that get imported and rebuilt across branches, so a check in place to look for this is a good idea.  I'm not sure if the unexpanded macro ends up in the header data, but I will check that first.

Do you have an example package I could use to recreate the problem?

**Comment by cipherboy** [comment]
My example package was `pki-servlet-engine` in internal dist-git, `rhel-9.0.0-alpha` branch. But I never got a successful RPM build; this was caught by `brp-mangle-shebangs` for me. 

I'm not aware of any package that successfully builds with unexpanded macros (yet), but I also didn't go looking. Since you mentioned having a large dataset for runpath, maybe it'd be good to double check all packages and see if there's an example in Fedora?

**Comment by dcantrell** [comment]
I have tried many different ways to get a reproducer for this, but I don't think it's possible.  I have eliminated all brp-* scripts and it's just rpmbuild.  Here's an example that I did in a scratch tmux package.  In the %files section I did:

`/%{somethingdir}%{_bindir}/tmux`

That gets around the "must begin with /" error.  %{somethingdir} doesn't expand and rpmbuild does carry this in the file list, but then when it tries to create the payload it can't find `/%{somethingdir}/usr/bin/tmux`

Without any more ideas, I am closing this one.  I like the idea, but in order to get there I really need a reproducer that I can work with and I just haven't found a way to come up with one.
