### ISSUE TITLE
osci.brew-build.rpminspect.static-analysis fails on desktop test for subscription-manager

### ISSUE THREAD

**Issue by wottop** [rpminspect/rpminspect#373]
https://dashboard.osci.redhat.com/?filters=eyJ0eXBlIjoiYnJldy1idWlsZCIsImFjdGl2ZSI6WyJzdWJzY3JpcHRpb24tbWFuYWdlci0xLjI5LjExLTEuZWw5Il0sIm9wdGlvbnMiOnsic2tpcFNjcmF0Y2giOmZhbHNlfX0%3D#/search

The desktop test fails with 

http://artifacts.osci.redhat.com/testing-farm/bc70e4fa-7b07-4bb7-a1a4-afec295e3658/work-rpminspectZXMVR_/rpminspect/execute/data/desktop/output.txt

subscription-manager requires cockpit-ws which contains /usr/libexec/cockpit-desktop

We manually waive this test each time, but would like to have it be configurable in some way to avoid it.

**Comment by cnsnyder** [comment]
I think there could be many ways of achieving this without having to look for executables in the entire tree of dependencies (to solve this generically for all components). One way to do this would be to allow specifying in the rpminspect which dependency provides the required executable. This of course implies that rpminspect is able to access a current version of the specified rpm to check that it does in fact provide the required executable.

**Comment by dcantrell** [comment]
That's an interesting thought.  Actually, as long as the package carries a runtime dependency on the package providing the executable, we can use that.

But the problem comes in with what build to check.  rpminspect is operating on builds from a Koji environment, so when performing this check and it doesn't find the executable in any package in the build where does it get Require'd packages?  Does it get them from a yum repo somewhere or does it ask Koji?  My thought would be the latter, but then rpminspect would need to get the latest successful build of the Require'd package from Koji to look through.

**Comment by cnsnyder** [comment]
Yea I'd tend towards the latter (retrieving the package for inspection from the last successful build in Koji). For anything in the gating world, we'd probably only want to check the last build that passed gating as well.

**Comment by dcantrell** [comment]
Looks like this is working with the latest rpminspect and a recent build of subscription-manager:

```desktop:
--------
1) Desktop file /usr/share/applications/subscription-manager-cockpit.desktop on noarch references executable /usr/libexec/cockpit-desktop; no subpackages
contain an executable of that name, however it has a TryExec key so it may be ignored in case ec=/usr/libexec/cockpit-desktop does not exist 
Result: INFO
Waiver Authorization: Not Waivable

Suggested Remedy: Refer to the Desktop Entry Specification at https://standards.freedesktop.org/desktop-entry-spec/latest/ for help correcting the errors and
warnings```
