### ISSUE TITLE
Gating test starting complaining the .egg-info changed from text/plain to inode/directory

### ISSUE THREAD

**Issue by bcl** [rpminspect/rpminspect#404]
```
rpminspect version: 1.5-0.1.202104292114git.fc34 (with data package: 1:1.5-0.1.202105052001git.fc34)
rpminspect profile: none
new build: pykickstart-3.16.12-1.el8
old build: pykickstart-3.16.11-1.el8 (found in rhel-8.5.0-z brew tag)

Test description:
Compare MIME types of files between builds and report any changes for verification.

======================================== Test Output ========================================

types:
------

1) MIME type on /usr/lib/python3.6/site-packages/pykickstart-3.16.12-py3.6.egg-info was text/plain and became inode/directory on noarch

Result: VERIFY
Waiver Authorization: Anyone

Suggested Remedy:
In many cases the changing MIME type is deliberate.  Verify that the change is intended and if necessary fix the spec file so the correct file is included in the built package.


Error: exec session exited with non-zero exit code 1: OCI runtime error

```

**Comment by dcantrell** [comment]
For completeness since we discussed this on IRC:

In the .11 build the *.egg-info entry is a text file.  In the .12 build the *.egg-info entry is a subdirectory which contains multiple text files.  I am also going to assume this is Python internalage with regard to egg-info content.  Nonetheless, the message from rpminspect is technically correct.  It reports the MIME type strings that libmagic returns, which is why it says "inode/directory" instead of just "directory".  I could get in to string munging from libmagic, but how that generally goes is libmagic will then decide to call it a directory/inode and everything will break.  So I'd rather not.

What I am doing now is making sure you add something like this to a local rpminspect.yaml file:

```
---
types:
    ignore:
        - *.egg-info
```

And then stop seeing these messages as Python developers change what the internals do.  Patch forthcoming.

**Comment by dcantrell** [comment]
Merged an enhancement that adds ignore list support for the types inspection.  I also support relative ignore globs now, so you can do this:

```
types:
    ignore:
        - "*.egg-info"
```

Rather than the whole /usr/lib/python*/blah/blah/blah stuff.  Note that this is YAML and YAML is terrible, so you have to write the glob in double quotes to appease libyaml because we can't have nice things.
