### ISSUE TITLE
rpminspect XML test makes no distinction between well-formedness vs validity

### ISSUE THREAD

**Issue by davidmalcolm** [rpminspect/rpminspect#455]
e.g. I'm seeing (in):
http://artifacts.osci.redhat.com/testing-farm/0f659fd0-4ac7-4fe6-ba98-cd9a86e2b5f3/work-rpminspectYyGIv_/rpminspect/execute/data/xml/output.txt

xml-files:
----------
1) File /usr/share/doc/libstdc++-docs/html/manual/policy_based_data_structures_test.html is a malformed XML file on x86_64

Result: VERIFY
Waiver Authorization: Anyone

Details:
Element img does not carry attribute alt

As far as I can tell the document is well-formed, but it appears it may be invalid (am having trouble downloading the schema when running xmllint locally)
See e.g. https://stackoverflow.com/questions/134494/is-there-any-difference-between-valid-xml-and-well-formed-xml

**Comment by dcantrell** [comment]
I am no xml expert and what rpminspect is doing is largely inspired by rpmdiff, but with the distinction of using libxml directly as opposed to running xmllint.

I think the xml check in rpminspect should probably stick with well-formedness and that be pass/fail but invalid would be an INFO reporting since determining validity is largely dependent on the tool consuming the xml data and rpminspect may not have everything required.

I am open to suggestions on how to adapt this to be more useful.  At one point I was questioning the value of this check in rpminspect in the first place, but I feel there is some value to it because xml is still used by a wide range of software for backend data and we probably want to make sure the package building process has not messed up the packaged xml files.

**Comment by dcantrell** [comment]
This also looks to be very similar to, if not the same as, issue #449
