### ISSUE TITLE
Adjust return codes on SEVERITY

### ISSUE THREAD

**Issue by morucci** [rpminspect/rpminspect#47]
Hi, 

Thanks for the extended explanation in https://github.com/rpminspect/rpminspect/issues/46#issuecomment-532704182

My use case is I want to give to packagers that use the Pull Request model on Pagure for distgits an early feedback on the quality of a PR change. This can help to reduce the amount of packaging issues reported on bodhi. rpminspect is part of the sanity checks and the rpminspect check on PR should be, for most cases, informative.

The CI engine under the hood is Zuul and by default it will prevent a PR to land if at least a check ("job") fails. Zuul can be told to ignore a job result but at the end the user wont look at the ignored job's results. That why I think it is important to have fined grained error code in rpminspect to make sure he integrating program can take the right decision - make the job fail or success.

So I my use case, I think that only a RESULT_BAD should make the job fail (PR author will be forced to fix the issue to make the PR land). RESULT_VERIFY and others severities must be ignored the job should succeed. I bet that a conscientious packager will look at the rpminspect report even if the rpminspect job is a success.

> 
> 1    Adjust the return codes so that the RESULT_* severity_t is the return code. Or at least maps accordingly.
> 
> 2    Add a command line option indicating the result code level you want rpminspect to return non-zero for. For instance, if you pass "-e RESULT_BAD" it could mean that everything below RESULT_BAD is treated as exit code 0 and only RESULT_BAD findings return non-zero.

Solutions 2 or 3 are fine with my use case. A preference for 2 activated by passing --map-returncode-on-severity maybe ?

**Comment by dcantrell** [comment]
How rpminspect will be used is another factor in determining how the return codes will work.  When I started the project, the primary objective was to create a tool we could use for gating purposes.  So that meant that we should be able to programatically make decisions based on its findings.  I also built it so that developers could run it locally as a linter or debug tool and get things "clean" before submitting them to the build system.

I agree that RESULT_BAD should be the only thing that fails an rpminspect run, at least from the context of CI.  A RESULT_VERIFY finding is subjective, at best, and like you said is something that most packagers will want to look at anyway.  For CI integration, the findings could follow a traffic signal model like red, yellow, green.  A red display would be at least one RESULT_BAD was found, yellow would be at least one RESULT_VERIFY exists, and green would be neither found, just OK or INFO.  Of course, that is dependent on how the results are incorporated in to a CI system (like your json2html converter).

I do not really think mapping the RESULT_* values to return codes is a good idea.  I think that returning 0 or non-zero is sufficient for CI use and local interactive use.  The additional details will be in the output displayed.

I am ok with adding a command line option to move the failure threshold.  Like keep it at RESULT_BAD by default, but allow the user to shift that to RESULT_VERIFY.  That could potentially be useful for building security updates or updates for CentOS or RHEL where you want nothing to show up that needs verification.  I am just brainstorming here.

Thoughts?

**Comment by morucci** [comment]
Hi David,

Result trend is not supported by Zuul CI and I think this concept does not make sense with Zuul as its main purpose is to gate incoming (not yet merged) changes.
So yes the threshold controlled with the command line is totally fine regarding my case to get a return code of non zero in case of RESULT_BAD only.

Thanks a lot
Fabien

**Comment by dcantrell** [comment]
Alright, that seems fairly simple to implement.  I will add a command line option to control the result threshold that triggers a non-zero exit code.  Thanks for the feedback.

**Comment by dcantrell** [comment]
I have added the -t option:

    rpminspect -t BAD

Let me know if this works for Zuul integration.
