### ISSUE TITLE
Consider validating %config usage for files under /etc

### ISSUE THREAD

**Issue by cipherboy** [rpminspect/rpminspect#479]
Per discussion on IRC DM yesterday between myself and @dcantrell (Aug 2nd, 2021) -- consider adding a check to ensure files under `/etc` that aren't executable (like init scripts) and aren't READMEs use `%config` correctly.

The example given was `initscripts` package and `/etc/inittab` (though, I later learned that this file has gone out of use):

 It is and not marked configurable by the `initscripts` package despite being (effectively) a configuration file.

See also: https://src.fedoraproject.org/rpms/initscripts/blob/rawhide/f/initscripts.spec#_344 and https://man.cx/inittab(4)

This probably applies to several other packages and configuration choices. Some list of false positives would probably have to be maintained globally and allow per-package overrides of course. This probably should just be informational to begin with.

**Comment by dcantrell** [comment]
I'd like to add this, but as a part that can be enabled or disabled in the rpminspect.yaml file.  For this to work, rpminspect needs to know what a valid configuration file path prefix would be.  If a file falls in that prefix and is not executable and is not a README (or is this an example of a subset of files?), then ensure it uses %config in a certain way in the spec file?  Should the mechanism that checks the %config macro use a pattern that you can specify in rpminspect.yaml?  Different distributions may have different policy here, so the rpminspect.yaml file could carry a regexp to match the %config macro or something like that?

Thoughts?

**Comment by dcantrell** [comment]
This came up in another conversation today and the request was similar to the original request here.  However, I've found that there is not a clear policy on where config files should live and what things must and must not be config files.  If we look at /etc, we do allow non-%config content there as well as executable files.

Unless the packaging policy is updated with additional rules around what goes in /etc, there's nothing I can implement.  This is why the config inspection right now reports changes from things marked as %config rather than looking for things that should be %config.

I am going to close this issue, but if something changes in the packaging policy for at least Fedora we can revisit this request.
