### ISSUE TITLE
RFE: badfuncs - ignore file(s) only for specific function(s)

### ISSUE THREAD

**Issue by sharkcz** [rpminspect/rpminspect#573]
I would like skip reporting an issue from the badfunc check for one specific function in one specific file. If I understand it correctly, then you can only skip the whole test for specified files.

an example from s390utils
````
badfuncs:
---------

1) /usr/sbin/qethqoat may use forbidden functions on s390x

Result: VERIFY
Waiver Authorization: Anyone

Details:
Forbidden function symbols found:
	inet_ntoa
````
The function is used in a safe way in the `qethqoat` binary, thus I would like to define an exception from the test just for this file and this function. Like to move the `ignore:` key from the `badfuncs` level one level down to the specific function.

**Comment by sharkcz** [comment]
works for me, thanks :-)

**Comment by omajid** [comment]
Additional RFE: would it be possible to use globs/regexes in the paths here?

I would like to exclude `/usr/lib64/dotnet/shared/Microsoft.NETCore.App/6.0.2/libcoreclr.so`, but there's a few challenges here. I would like to be able to select `/lib/` for 32-bit platforms. There's also a version (`6.0.2`) in the path that changes between builds. It would be great if I could exclude something like `/usr/lib(64)?/dotnet/shared/Microsoft.NETCore.App/6.[[:digit:]]+.[[:digit:]]+/libcoreclr.so` or something similar

**Comment by hroncok** [comment]
We would like to skip ipv4-only check for `/usr/lib*/python*/lib-dynload/_socket.*` in badfunc as well, without skipping the entire check. This is worse in pypy, where we need to exclude the entire libpypy because of some bad ipv4-only functions we know about are there. We'd like to benefit from the *other* badfunc checks without the need of skipping all of them fo a particular file.
