### ISSUE TITLE
RFE: Checks for insecure crypto use and implementations (aka SHA-1)

### ISSUE THREAD

**Issue by Jakuje** [rpminspect/rpminspect#577]
Right now, we are trying to audit usage of SHA-1 across the packages, which is not much more than a `grep -i -H -n -C 5 -r 'SHA[-_]\?1'` on content of the SRPM after the `prep` phase and manual review of the results. It indeed yields many false-positives so it might need to narrow-down the search or categorize different matches with some heuristics (function definition, the actual implementation of algorithm, constant loaded from OpenSSL, ...). It certainly need some concepts of waiving both false positives and non-security uses.

It could be simply extended for MD5 checking, which is no better, but it is still widely used and easy to grep for. Additionally, we might need to come up with some other algorithms that we will need to audit/check for/remove in the future.

As far as I know, this should be possible to do with `rpminspect` with something similar as done in `inspect_unicode`. I am raising this issue mostly to start discussion whether it is a good place to start this work, whether there are some pointers or ideas or suggestions before I start proposing changes or drafting some pull requests.

**Comment by dcantrell** [comment]
Are you checking for shared library symbols in ELF objects?  If so, you can use the badfuncs inspection to check for any of the known function names.  Just add them to the list in the configuration file and rpminspect will report if any of the symbols show up in the ELF objects.

This might be more useful since the code might contain code that calls SHA-1 functions, but it might not be enabled in the build.

Obviously the above will not work for any code that implements SHA-1 or MD5 directly, so a mechanism similar to what the unicode inspection does would be required.  It might be hard to implement from a practical standpoint because it would ultimately rely on developers using somewhat similar function naming.  And that may not happen.  Still, implementing this check in rpminspect is entirely possible and it might even make sense to implement it as a generic source code scanner where you supply a list of regular expressions that rpminspect can check code for.  That could be combined with a list of exceptions to ignore.

**Comment by Jakuje** [comment]
Thank you for the suggestion. You are right. Checking the ELF objects might raise less false positives (from comments, non-build artifacts, ...). I will certainly investigate this direction. This can work for example for OpenSSL's `MD5` or [`SHA1`](https://www.openssl.org/docs/manmaster/man3/SHA1.html) functions, but there are dozen of other ways to get SHA1 from OpenSSL and even more from other libraries.

For implementations, this might be harder, as it would require some regex in the badfuncs inspector, which I think is not in place right now and which will certainly yield false positives.

**Comment by dcantrell** [comment]
Sounds good.  Feel free to email me or find me on IRC if you have any questions about the badfuncs inspection.

As for the source code scanning... that will be involved and I know there are projects that have attempted to do this.  Internally at RH, I know of the PELC project.  There may be others.
