### ISSUE TITLE
Complains about file changes in a "non-rebased build" when the build was rebased (git snapshot incremented)

### ISSUE THREAD

**Issue by AdamWill** [rpminspect/rpminspect#579]
See https://osci-jenkins-1.ci.fedoraproject.org/job/fedora-ci/job/rpminspect-pipeline/job/master/59817/testReport/(root)/tests/_changedfiles/ .

    new build: openqa-4.6-68.20211130gitf004793.fc35
    old build: openqa-4.6-67.20210804git6541adf.fc35 (found in f35-updates koji tag)

but then:

"1) File /usr/share/doc/openqa-doc/ContainerizedSetup.asciidoc changed content on noarch.  Please verify this change was deliberate for a non-rebased build."

etc. etc. etc. Does rpminspect not know that the date increasing and the git revision changing indicates a rebase?

**Comment by dcantrell** [comment]
rpminspect does not know that an increasing date stamp in the Release field indicates a rebase.

How rpminspect determines if you have rebased a package or not is if the Name values match but Version does not match.  An update and non-rebased package has a matching Name and Version field.  In both cases, Release can be anything.

There's no real good way to reliably do this in rpminspect since the packaging committee rules may change from time to time.  I decided the most consistent way to determine if something was rebased was to compare Version.

I'm open to ideas for how to handle this in a more reliable way.  You can disable the changedfiles inspection for the openqa package as well.

**Comment by AdamWill** [comment]
the package naming rules relating to snapshots haven't changed substantially for a *long* time, IIRC. shipping git snapshots is not uncommon, it seems like a fairly large gap to just not handle them...

**Comment by AdamWill** [comment]
edit: well, scratch that, I forgot they introduced the whole [weird character nonsense](https://docs.fedoraproject.org/en-US/packaging-guidelines/Versioning/#_handling_non_sorting_versions_with_tilde_dot_and_caret) a few releases back. I guess I'll see if we can do something with that.

**Comment by dcantrell** [comment]
The only thing I can really think of adding is an optional configuration file setting that lets you tell rpminspect how it should determine if something is rebased.  I don't want to rely on the packaging guidelines to never change.  Because they will.  But if we can generalize something and turn it in to a config file block, I'm all for that.

Maybe it could be tell rpminspect what each field has to do to be considered a rebase:

```
---
rebase:
    name: match
    version: any
    release: differ
    epoch: any
```

The default could continue to be name=match, version=differ, release=any, epoch=any.

**Comment by dcantrell** [comment]
@AdamWill any thoughts of the suggested implementation?  The package maintainer could put a rebase block in the rpminspect.yaml file for the package to instruct rpminspect how to determine if a package is rebased or not.

**Comment by AdamWill** [comment]
Oh, sorry, I forgot to reply before going on shutdown! Well, that's not a bad design, though it would mean that really *any* change to the package would now be taken as a rebase, even if the snapshot date *didn't* change...

Would it be possible to do something like just looking for valid YYYYMMDD dates in the release field, and if there is a valid date in both release fields and it differs, considering that a rebase? Or is that getting too fancy?

**Comment by dcantrell** [comment]
I would prefer to not add Fedora packaging policy stuff in to librpminspect directly.  As it is, rpm does not treat the Release field in any special way.  It's just a string.  Everything we have defined in Fedora packaging policy is on top of that.  That's fine, but I would like to implement some kind of way for rpminspect that lets us define Fedora packaging policy like this as a rule.  So a regular expression or something like that.

This could just go in the main configuration file too.  Like all of the possible ways to determine if a package is rebased in addition to what it's already doing.

This may sound like overkill, but it will save a lot of pain later on because adjusting packaging policy then becomes a matter of updating configuration files as opposed to patching code.

So the example you have here, the rule is basically name and version match but if the release matches ^[0-9]{8}git[0-9a-f]{6}\..* and differs between builds, it's a rebase.  Right?  If so, how can that be expressed as a configuration file setting?

20211130gitf004793

**Comment by AdamWill** [comment]
well, yeah, except that I was gonna simplify it to just `[0-9]{8}` that datetime (or whatever) reckons is a valid date.

Still, on the whole, it might just be simpler to switch to the new style from the guidelines, since that involves putting the date in the Version, so it'd work with rpminspect...

**Comment by dcantrell** [comment]
I looked at the openqa package and I see you have adopted the new Fedora Packaging Guidelines versioning system and the github info is now part of RPMTAG_VERSION.  With that I am going to close this RFE out since there's nothing to do on the rpminspect now.  Thanks for entertaining my ideas and brainstorming in this issue.
