### ISSUE TITLE
Check that the dist tag uses the correct value

### ISSUE THREAD

**Issue by tyll** [rpminspect/rpminspect#58]
When checking the EVR allow to check that the dist tag uses the right value, for example builds for Fedora 31 should use fc31.

**Comment by dcantrell** [comment]
Koji doesn't give the expanded disttag in its output, but I think we can use the build target and derive a disttag from that.  Here's what I'm thinking:

1) Expand the Koji data gathering in rpminspect so it picks up the build target name when it gathers the rest of the data.
2) Define rules in rpminspect.conf on how to transpose a build target to a disttag.  Or just add a 1:1 mapping.
3) When rpminspect is able to get a build target, fill in the release string in struct rpminspect as our expected disttag value.  The -r command line option should still override this though.

Right now rpminspect works when comparing two builds within the same build target because it derives the disttag value from the Release tag in the RPM headers.  If they don't match, then it knows you are comparing two builds from different build targets.

In rpminspect.conf, I am thinking it can either carry a 1:1 mapping of targets to disttags.  Such as:
f32-build = fc32

Or a transpose rule, like:
f${RELEASE}-build = fc${RELEASE}

Either way, this mapping information will have to be maintained just like the rest of the data in rpminspect-data-fedora.

Thoughts?

**Comment by dcantrell** [comment]
I would still like to implement something here, but I think it's going to require some contributions to the Koji API to have it report out the dist tag as expanded in the mock environment used for building.  I don't think that's impossible, but that would be the first step before I can do anything in rpminspect.

I have opened https://pagure.io/koji/issue/2760 requesting this functionality in Koji.

**Comment by hroncok** [comment]
> In rpminspect.conf, I am thinking it can either carry a 1:1 mapping of targets to disttags. Such as: f32-build = fc32
> 
> Or a transpose rule, like: f${RELEASE}-build = fc${RELEASE}
> 
> Either way, this mapping information will have to be maintained just like the rest of the data in rpminspect-data-fedora.
> 
> Thoughts?

Just a note: A valid Fedora 37 dist tag might as well be `fc37~bootstrap`.

**Comment by dcantrell** [comment]
dist tags are pretty fluid and we have a rough pattern we follow, but we are deliberately not that strict.  I don't think a check here can be implemented reliably after thinking about this for a while.  If someone has a better idea, please let me know.
