### ISSUE TITLE
Help needed with a rpminspect result

### ISSUE THREAD

**Issue by morucci** [rpminspect/rpminspect#59]
Hello David,

I'm moving forward by adding some new packages into Zuul CI and the rpminspect job. Here is a distgit change on a package called Nodepool  https://src.fedoraproject.org/rpms/nodepool/pull-request/2 and I'm not sure how I could fix issues reported by rpminspect, I guess that's because I'm not familiar enough with rpmdiff/rpminspect. Could you please have a look to help me understand the report ?

First issue (reported as BAD severity) is such as: "Packages should contain files or directories starting with `tmp/` on noarch" and appears multiple time.
Second issue (reported as BAD severity) is such as: "Upstream source file `builder-logging.yaml` changed content". builder-logging.yaml is part of the distgit repository, a SOURCE file, yes it changed since the last published version of Nodepool on Koji but that's expected.

Here is the report https://fedora.softwarefactory-project.io/logs/2/2/a09b4e0487082c794340e618598d77e0a6f5ebfb/check/rpm-rpminspect/e0ad618/rpminspect.html

Thanks in advance for you help :)

Fabien

**Comment by dcantrell** [comment]
> I'm moving forward by adding some new packages into Zuul CI and the rpminspect job. Here is a distgit change on a package called Nodepool https://src.fedoraproject.org/rpms/nodepool/pull-request/2 and I'm not sure how I could fix issues reported by rpminspect, I guess that's because I'm not familiar enough with rpmdiff/rpminspect. Could you please have a look to help me understand the report ?

Sure thing.  And thanks again for the feedback on rpminspect.  It's really helpful getting some real world cases.

> First issue (reported as BAD severity) is such as: "Packages should contain files or directories starting with `tmp/` on noarch" and appears multiple time.

A couple of things here.  I should fix the string because it should say "Packages should not contain files or directories starting with tmp/".  Second, the message should indicate what file or directory is in question.

Now, as for the actual catch.  This part of addedfiles is looking at package members to see if any paths have a prefix as defined in forbidden_path_prefixes in /etc/rpminspect/rpminspect.conf.  Right now that is set to "tmp/ var/tmp" on Fedora systems meaning packages can't own files in those directories.

This may be a real packaging error or an allowed exception.  If it's an exception, we probably don't always want rpminspect reporting it.  I have the data package, rpminspect-data-fedora, that is meant to carry this sort of data.  The question now is whether or not this is something worth carrying in the data set in a generic sense or should this be tracked per package.  I have been wanting to set up per-package waivers or exceptions like this so this might be a good opportunity for it.  On the other hand, having the exception tracked in rpminspect-data-fedora allows for more oversight on packaging policy deviations.  What are your thoughts on this?

> Second issue (reported as BAD severity) is such as: "Upstream source file `builder-logging.yaml` changed content". builder-logging.yaml is part of the distgit repository, a SOURCE file, yes it changed since the last published version of Nodepool on Koji but that's expected.

How was rpminspect invoked?  For the upstream inspection to run, it would have to have two builds to compare.  I assume you did that here, but I want to see the command line that invoked it.

I may need to adjust the upstream inspection some here.  It's really more useful for updates to stable releases where the upstream source archive didn't change but you added a patch.  In this case it might not be as useful since those files will always be changing.  I have received feedback from people wanting this check to remain, but maybe rather than BAD it should be a VERIFY?

**Comment by dcantrell** [comment]
It's been a while, but while working on this one I found some problems with the peer detection routines in librpminspect.  I think this was causing invalid peer package matching which would explain invalid reporting.

Can you try the latest build in my Copr repo and see if this problem continues?

**Comment by dcantrell** [comment]
And my Copr repo is here:
https://copr.fedorainfracloud.org/coprs/dcantrel/rpminspect/

**Comment by morucci** [comment]
Hello David,

Here is a report I got today with the packages:
- librpminspect-0.8-0.1.201911121951git.fc30.x86_64 
- rpminspect-0.8-0.1.201911121951git.fc30.x86_64
- rpminspect-data-fedora-1:0.6-0.1.201910171955git.fc30.noarch
I'm using the "dcantrel/rpminspect" copr in the job so I guess that's the right versions - please confirm.

Report: https://fedora.softwarefactory-project.io/logs/4/4/f5b26dfdf869c4634be9c007af945eae9ac533f6/check/rpm-rpminspect/130734c/rpminspect.html

For the first issue, I still get a BAD issue for a bunch of files with messages such as:
Message: Packages should not contain not files or directories starting with `tmp/` on noarch: /etc/sudoers.d/nodepool

The second issue seems to be there too with some BAD issues with message such as:
Message: Upstream source file `nodepool-builder.service` changed content
This service file is part of the distgit, not from the source.

Thanks for your help

**Comment by dcantrell** [comment]
Yep, that is the correct version.  This is good feedback.  I'm continuing to debug the issue now.  I am first working on the tmp/ catch because that one is really odd to me.  More after I work on it a bit.

**Comment by dcantrell** [comment]
OK, first update.  I see in the output that the License inspection is not reporting the package NEVRA.  I was incorrectly using headerGetString on RPMTAG_NEVRA, which you can't do since it's an RPM extension header tag.  I've added get_nevra() to rpm.c in librpminspect to handle this for the rpminspect code that needs it.

This fixes these strings:
Valid License Tag in (null): ASL 2.0

It now gives the package NEVRA instead of (null).

On to the next part...

**Comment by dcantrell** [comment]
I am not seeing the tmp/ BAD result locally:

[dcantrel@awvr rpminspect]$ ./build/rpminspect -T addedfiles ./examples/nodepool-3.0.0-6.fc32 ./examples/nodepool-3.0.0-7.fc32
added-files:
------------
Result: OK

Can you check and see that your /etc/rpminspect/rpminspect.conf file is the latest?  If there is a .rpmnew version of the file there, maybe copy that one to /etc/rpminspect/rpminspect.conf and see if the problem shows up again.

**Comment by dcantrell** [comment]
Also, I get Result: OK on the upstream inspection results.  I don't get any BAD results for it.

**Comment by morucci** [comment]
The versions I'm checking are not the same in your test, the diff is between nodepool-3.0.0 and nodepool-3.9.0. See here for the exact versions https://fedora.softwarefactory-project.io/logs/4/4/f5b26dfdf869c4634be9c007af945eae9ac533f6/check/rpm-rpminspect/d6c1bbb/job-output.txt.gz#_2019-11-13_16_47_40_254041

This generates this report: https://fedora.softwarefactory-project.io/logs/4/4/f5b26dfdf869c4634be9c007af945eae9ac533f6/check/rpm-rpminspect/d6c1bbb/rpminspect.html

You can download the 3.9.0 packages built from Koji here: https://fedora.softwarefactory-project.io/logs/4/4/f5b26dfdf869c4634be9c007af945eae9ac533f6/check/rpm-scratch-build/c4a9968/buildset/

**Comment by dcantrell** [comment]
Ah ha, ok, let me run with that and see what I can do.  Thanks!

**Comment by dcantrell** [comment]
Update here... I have found and fixed the problem where it was reporting tmp/ files.  Validated against the packages you've been using and it no longer incorrectly reports that.  On to the upstream issue...

**Comment by morucci** [comment]
Hi David,
Yes the tmp/ issue is gone in the last run: https://fedora.softwarefactory-project.io/logs/2/2/aefae72e5fb73df94a7126fc9a32fdb6622a5657/check/rpm-rpminspect/cffcec1/rpminspect.html

**Comment by dcantrell** [comment]
Great to hear.  On the last issue where it reports source files have changed between builds, it is actually correct.  However, it reports it as BAD.  I think this is more correctly reported as a VERIFY.  The source files in question are listed in Source*: lines in the spec files, which is why rpminspect looks at them.  It only does the upstream comparison for Source files listed in the spec.

What I think it should be doing here is:
1) Reporting the change as a VERIFY.
2) For Source files that are text, show a diff(1) of the change.  For Source files that are archives or otherwise non-text, just report that it changed from the before to after build.

What are your thoughts here?  The main purpose of this inspection is to report changes between builds when you do not want a rebase to happen.  rpminspect does not know what kind of comparison you are doing, so maybe a command line option could be added that lets you specify if you want to enforce a "no rebase" rule.  In that case, changes between the sources would be reported as BAD.  If rebases are allowed, changes would be reported as VERIFY.

**Comment by dcantrell** [comment]
OK, diff(1) output is now collected for changing source files if the source files are text files.  This is shown in the results output.  I also changed it from BAD to VERIFY since that seems more appropriate.

I'm going to call this issue done.  Anything new that comes up, please open up a separate issue.  Thanks for the feedback in this one.  This report covered a lot of things I was able to fix up.
