### ISSUE TITLE
Add support for scratch builds

### ISSUE THREAD

**Issue by thrix** [rpminspect/rpminspect#60]
Looking at sources, seems rpminspect does not support scratch builds. I am also reading the man page, but there is no hint (or workaround) how to test scratch builds.

**Comment by dcantrell** [comment]
This is a problem.  I need to extend rpminspect so it can handle task IDs, which is the only way to reliably get scratch build info from Koji.  I will work on a patch for this.

Currently, the only way to work around this issue is to download the build manually from Koji (rpminspect will not be able to) and cache it locally as rpminspect would, then run rpminspect and give it that local build directory.

**Comment by thrix** [comment]
@dcantrell thanks for the explanation, we will keep running rpminspect for non-scratch content only and we can revisit once it is possible to use task ID. I think it is not worth so much workarounding in our code now.

**Comment by dcantrell** [comment]
I've been working on this today after fixing the other memory problems.  I have to call getTaskInfo, then getTaskDescendents, then getTaskResult for each descendent.  Once I have all that info I will have a list of packages for the build and can pass it on.  Should have it done next week.

**Comment by dcantrell** [comment]
I've got this working today.  I'm going to push it, but I am still working on it.  There are some memory leaks with my usage of xmlrpc-c and I just need to trace all of that and clean things up.  It runs, it's just leaking at the moment.
