### ISSUE TITLE
xmlrpc_struct.c assertion failed

### ISSUE THREAD

**Issue by ukulekek** [rpminspect/rpminspect#61]
Hi David!
I got a bug:
```
$ rpm -q rpminspect
rpminspect-0.8-0.1.201911131926git.fc29.x86_64
$ rpminspect rhosp-director-images-15.0-20191114.1.el8ost
...
../src/xmlrpc_struct.c:664: assertion failed
Aborted (core dumped)
```
I have no idea how to debug it. Could you look at this?
Thank you in advance!

**Comment by dcantrell** [comment]
Looking at this one now.

**Comment by dcantrell** [comment]
Getting the build ID of this build, I do:

xmlrpc http://INTERNAL_KOJI_HUB listBuildRPMs "i/1011228"

And get the expected results back.  It returns an array of 9 structs, which I then iterate over reading the information in each.  It is failing here on the last array member and on the 14th struct element, so I need to dig in to this a bit more.

**Comment by dcantrell** [comment]
Oh, I see.  OK, so the 'size' element of one RPM in this build is returning as a 64-bit integer whereas the other ones are all integers.  I don't think I've hit that before with Koji, so I need to extend it to support that.  Should be a simple fix here.

**Comment by dcantrell** [comment]
Well that was a really fun one to track down.  Thanks for the report.  I have fixed this issue and the commit will show up here shortly.  Then builds will happen in Copr.

The main problem is that Koji is returning either an XML int32 or int64 type for the size rather than just always using an int64.  In the year of work I've put in to rpminspect, I have only ever seen int32.  The build you used had one RPM in the list that had an int64 size type.  Fortunately those are the only two int types in XMLRPC.

I have modified the koji.c code to handle int32 and int64.  I'm storing the resulting value as a long long int.  Right now that doesn't matter since I don't use the RPM size anywhere in librpminspect.
