### ISSUE TITLE
When will rpminspect increase the version of annocheck that it uses?

### ISSUE THREAD

**Issue by mulkieran** [rpminspect/rpminspect#666]
We encountered a problem where annocheck could not properly identify our executables during builds.

We have been told that the problem has been fixed in annobin 10.55[1].

We are wondering when we will be able to verify the fix.

We noticed that the version of rpminspect that runs on our f37 builds is itself an f36 package, and are not sure how that might influence the answer to our question about annocheck.

[1] https://bugzilla.redhat.com/show_bug.cgi?id=2057737

**Comment by dcantrell** [comment]
rpminspect itself doesn't have a hard requirement on the version of annocheck it uses.  It's simply a Requires in the package spec file.

The environment where rpminspect runs for Fedora, CentOS, or RHEL controls what gets installed.  I think I'm going to update the Developer Guide because this is moderately confusing to a lot of people, and I get it.  rpmdiff was a self-contained system you submitted jobs to and waited for a result.  rpminspect is first a tool that can be installed and run anywhere.  It is version-independent of what you are checking (also unlike rpmdiff).  How we use rpminspect in the various gating environments is just an implementation aspect for those systems.

For Fedora rpminspect gating jobs, this image is used to run the program:
https://github.com/fedora-ci/rpminspect-image

Looking at that Dockerfile, I see they are building an F36-based image.  They pull current rpminspect-data-fedora and rpminspect packages from Copr.  And then that's the environment where the rpminspect gating job will run.

It's not necessary for the environment where rpminspect runs to match the target you build for.  An F36 image is capable of running rpminspect on F37-targeted packages.  The rules are defined in rpminspect-data-fedora.  This was a big change I wanted to make sure was in place for rpminspect compared to rpmdiff because rpmdiff was *very* particular about its runtime environment.  RHEL6 packages had to be checked on RHEL6, etc.  rpminspect does not have that requirement.

I went to Bodhi to look for the latest version of annobin in F36 and it looks like it's 10.54, so that is likely the issue here.  The annobin team needs to release an update in F36 to bring the version up to at least 10.55.  I see that 10.57 and 10.58 builds are available in F37, so I guess they just aren't doing F36 updates unless someone asks for it.  If you ask the annobin team for an update in F36, I imagine they would be ok with that.
https://bodhi.fedoraproject.org/updates/?search=annobin
