### ISSUE TITLE
Product release detecting problem

### ISSUE THREAD

**Issue by ukulekek** [rpminspect/rpminspect#72]
Hi!
Whenever I run:
```
rpminspect redhat-release-atomic-host-7.8-20190910.1.atomic.el7.2 redhat-release-atomic-host-7.8-20190910.1.atomic.el7.0
```
I get:
```
*** Builds have different product releases (2 != 0)
```
In this case, the expected result should be:
```
*** Builds have different product releases (el7.2 != el7.0)
```
Then, I tried to add `el7 = ^el7.*$` to the config. The expected result, in this case, is executing the test, but I get the same error. 
I suppose the rpminspect expects the product release is placed after the last dot.

**Comment by dcantrell** [comment]
Correct.  What it does is look at the Release tag and it takes the end of the string starting at the first '.'.  The obvious problem there is dist tags that contain a period.

RPM does not store the dist tag separately in the header like it does with other tags (e.g., modularitylabel).  We don't define 'dist' as a %global at build time, so we can't use it.  Without that, I have to trim the Release string.

What I could do is expand on the regex matching here.  So instead of taking the right most period, I could look for the substring that begins with "KEY." where KEY is the left side of the equal sign in the rpminspect.conf file.  In this case it would be the substring "el7.".  Then if the substring from the beginning of that to the end of the string matches the regexp, we can call it release KEY.

Let me see what I can work up here.

**Comment by dcantrell** [comment]
Yeah, ok, that was easy.  Patch coming in a couple minutes.  I am updating the rpminspect-data-redhat package first.
