### ISSUE TITLE
FILES CHANGED test is too sensitive?

### ISSUE THREAD

**Issue by t8m** [rpminspect/rpminspect#74]
If the test should be used for gating and we are not expected to have to always waive it I do not see a point reporting that files changes as something that needs inspection.

**Comment by thrix** [comment]
CI results which triggered this bug: https://url.corp.redhat.com/rpminspect-issue-74

**Comment by dcantrell** [comment]
As implemented, the changed files inspection is going to report these changes.  I agree that it is a bit too pedantic for gating purposes.  The intent in rpmdiff was to prevent unexpected file changes once a RHEL release went out the door.  To me that makes sense because we do not necessarily want to do drastic changes to each package in a .y release.  But this makes it impossible to do work on a .0 release in the context of gating.

Given the two use cases, what I have been thinking of is implementing rpminspect profiles.  This is a way to define the inspections to run by specifying a category.  In the case of gating, I don't think the changed files inspection is very useful.  We will always change things.  But when it comes to maintenance work, we want to catch any file changes and verify those.

So, what if rpminspect had an option like -P/--profile that let you specify a runtime profile.  For example:

rpminspect -P gating
rpminspect -P maint

The rpminspect.conf file could let users define profiles but rpminspect could also have some built in by default.

Thoughts?

**Comment by thrix** [comment]
Seems the right time to start thinking about which tests we want to gate on. I like the ideas of profiles and that we provide some sane defaults for bot RHEL and Fedora. So :+1:  from me.

**Comment by sharkcz** [comment]
I've met this problem today and have few thoughts about it
- when we are updating a package, then having changed files is expected, binary files change even without a source code changes, the maintainer can't influence it and it makes little to no sense to have a test that will never pass
- for the spec file it should warn when it hasn't been changed, except special situation (like playing with disttag) a new build means a changed spec file

**Comment by dcantrell** [comment]
So thinking on this one a bit more.  My original plan was for rpminspect runtime profiles to allow rpminspect.conf settings per profile.  I'm still going to do that as a separate RFE, but I think that this issue can be handled with some simple tests.

For example, I think that the changedfiles test should only run if at least one of these conditions is true:
1) The file in question has a prefix from security_path_prefix in the rpminspect.conf file
2) The RPMTAG_VERSION from the before and after build are the same

If it's not a security path prefix file and the package versions are different, the inspection is skipped.  This would avoid the unnecessary noise for package updates that are always going to happen, but still contain a check in place for security-related files.  But it would run for packages where the version number is the same but the release has changed, that can be viewed as a maintenance operation rather than a rebase and changes should be more conservative.  This is not always true (e.g., rawhide), but I think this is a reasonable policy for now.

A question I have is whether or not keying on comparing the RPMTAG_VERSION is sufficient.  Should I also look at the epoch?

**Comment by dcantrell** [comment]
> I've met this problem today and have few thoughts about it
> 
>     * when we are updating a package, then having changed files is expected, binary files change even without a source code changes, the maintainer can't influence it and it makes little to no sense to have a test that will never pass

Agreed, see my comment above.  I think my idea there will take care of most of the noise you are seeing.

>     * for the spec file it should warn when it hasn't been changed, except special situation (like playing with disttag) a new build means a changed spec file

I think that source packages should be skipped in the changedfiles inspection.  There's a separate inspection for upstream source checking, there is one in the works for patch comparison, and there is a separate set of tests for spec file specific things.

Thoughts?

**Comment by sharkcz** [comment]
> So thinking on this one a bit more. My original plan was for rpminspect runtime profiles to allow rpminspect.conf settings per profile. I'm still going to do that as a separate RFE, but I think that this issue can be handled with some simple tests.
> 
> For example, I think that the changedfiles test should only run if at least one of these conditions is true:
> 
>     1. The file in question has a prefix from security_path_prefix in the rpminspect.conf file
> 
>     2. The RPMTAG_VERSION from the before and after build are the same
> 
> 
> If it's not a security path prefix file and the package versions are different, the inspection is skipped. This would avoid the unnecessary noise for package updates that are always going to happen, but still contain a check in place for security-related files. But it would run for packages where the version number is the same but the release has changed, that can be viewed as a maintenance operation rather than a rebase and changes should be more conservative. This is not always true (e.g., rawhide), but I think this is a reasonable policy for now.
> 
> A question I have is whether or not keying on comparing the RPMTAG_VERSION is sufficient. Should I also look at the epoch?

This new approach looks good to me. I maintain a package that keeps version and adds large backports and find the size check useful in such situation.

With epoch I think it's very unlikely to keep version and bump only epoch, they should be changed together.

There is one case where generic checking the file size changes makes sense. Some issues in the toolchains might cause sudden size increases of the files, for example broken strip will leave binaries unstripped, excessive amount of notes will be added or similar. I vaguely recall seeing something like that in the past in Fedora. Question is whether this should be checked on package/rpm level or on distro/compose level.

**Comment by dcantrell** [comment]
For clarification, the file size check is a separate inspection in librpminspect and it's not committed yet.  The changedfiles test does the following:

https://github.com/rpminspect/rpminspect/commit/06fde8ae50605e16293122e784ba22bf6db07654

debuginfo and debugsource packages are skipped for changedfiles.  I'm also adding in a skip for source packages.

**Comment by dcantrell** [comment]
Closing this issue, moved the runtime profile RFE over to issue #82
