### ISSUE TITLE
A ton of the same java byte code results

### ISSUE THREAD

**Issue by ukulekek** [rpminspect/rpminspect#75]
Hi!
I have observed a similar issue as https://github.com/rpminspect/rpminspect/issues/71 with java bytecode test.
Try this:
```
rpminspect -F json java-1.8.0-ibm-1.8.0.6.0-1jpp.1.el6_10 
```
In this case, I got a 80MB results file

**Comment by dcantrell** [comment]
I'm looking at the results and everything looks real.  77M of the results when I run it are from the javabytecode inspection.  I see this for every class file:

Java byte code version 52 greater than expected 43 for product release el6_10

If that needs to change, send a PR for rpminspect-data-redhat.  Right now only el8 and default are defined.  So that's my guess.  I don't know what el6 or el7 should be, but whoever does can send a PR to rpminspect-data-redhat.

**Comment by thrix** [comment]
@ukulekek can you open it against redhat-inspect-data? and we need to find somebody from java to provide the correct value ....

**Comment by dcantrell** [comment]
I asked someone today what the minimum JVM major versions should be for el6 and el7 and committed those to rpminspect-data-redhat, but verify them please and submit a PR if they need to be changed.
