### ISSUE TITLE
Shell-syntax checks binary files

### ISSUE THREAD

**Issue by ukulekek** [rpminspect/rpminspect#79]
Hi!
When I run:
```
rpminspect -F json java-1.8.0-ibm-1.8.0.6.0-2.el8 java-1.8.0-ibm-1.8.0.5.40-3.el8_0
```
I got shell-syntax results like this:
```
"shell-syntax": [
     {
       "result": "BAD",
       "waiver authorization": "Anyone",
       "message": "ibm-java-sdk-8.0-6.0-ppc64le-archive.bin is not a valid sh script on x86_64",
       "screendump": "tmpR55UAK\/artifacts\/java-1.8.0-ibm-1.8.0.6.0.WSwM8T\/after\/src\/java-1.8.0-ibm-1.8.0.6.0-2.el8.src\/ibm-java-sdk-8.0-6.0-ppc64le-archive.bin: line 3610: syntax error near unexpected token `$'\\276\\232\\350f\\344\\255''\ntmpR55UAK\/artifacts\/java-1.8.0-ibm-1.8.0.6.0.WSwM8T\/after\/src\/java-1.8.0-ibm-1.8.0.6.0-2.el8.src\/ibm-java-sdk-8.0-6.0-ppc64le-archive.bin: line 3610: `r<\u0018\F7\u001dI\F7U\f\D0?\u0019F\"\9E\8B\F6\8A\F5\/\u000b\E3\E6\985\B09]\ECD\B47]\DFM\F4\9A\AF\EE\C1\84\8F\A58F\F4\u000f`\E7\89\F6\DF!ZFt)Q\82\E8A\E0\BF%:\u000b\D7C\A9\9E,\C5?A\FA2\A2r\C2N\A7\F8Y\A2\CD\C0\CC\C7Dۡ\CC\"ރh:\AE\F7!z\9D\E8r\A2uDg\FA\F8\F8\u001fĿS\ED\F9p\D5\FBmQ\FF'DS\89^F^\u0005\E1[\E3\FA\BF\u0011\DF\EB\BB\F7i\A2^\\\FF\f\F1\D1D;\E0z\u0015\E2+\u0010\BF\84x\u0018\DA\EB!\FA\u000b\B0-\u0011\9FB\F4\u0014\AE\EB\u0011\FF\8Ah8\D1\C9HG\ADM\C3h\AA\F3a\8A7\u0010%\89\CE!z\92h;\B4\B5\u0016\E5\D6#ޝ\E8K\A2\BF\u0013\u001dNTI4\8A\CA\FE\88\E2?\u0013=J\F4>\D1n\A2\9D\B9D\9DD\E7\u0012\DDH\F4k\E0%\BA\80\E8*\A2v\A2\u0016\A2\B7\890l\AD\E7\88\EE'\BA\87hg\A2\u0003\88\EES\FD\CE\u000fuk>\D1\F1DC\b\FB\CA\D7\E6\u0017Ds\886\u0012\BDJt\u0010\D1E\C8۞\CA\EEH\F1\89D\DB\D0\F5C\82\DF-\b[\80\EB;\88\9A\88\9A\89\FEHt\u0018ѶDé\CC\C1\BE{v\"\E2\85\C73\88\95Kj\A0\F8\F7H?O\B4\86\E8#\A2\91\94\F7K\8A?%\DA\CA\D7\u001fvγ\u0011\u000f\88RDʕ\9CJ\D4F\D4O\F4\u0016\91r3U(\u0017\D1\F5D\BF@z\u0007\DC\u0006ҷ\u0010\r\C3u\80hW\\\FF\90\E8C\A2\9B\90~\C0뀾~\u0017X\98\E8\u0004\A2c\89F o\u0011\F2\CA(}\u001b\C5\FF$\FA\9C\E8\r\A2k\89\B6&\FCo\96\u0019.\B1\BE\9D0\E2y\FFV\u0005\B01߰\8E\AF\9B\DF\F7+\82\8F\F7]\FB׈?\u0018\A0\AEm\u0010\8F\u0012x\r\E2-\u00107\u0012\ED\E9\CBW\FE|\9E\/=\8B\E8@\A2C\89\F6%\9AF\B4\8B\/\/\"\BB@\FBj\u000e\E9\F0\A5\8F\u0011\F9u\u0005\EEq|\D7G\8A\BC\D6\u0002\E5\C7\u0015\C0T\88\u0010\u0005\89\FE\A3@\DEDģ\8Bܫ\u0003\E4\A9\D0E\F4S\A2I\u0002_J\B4D`\DDD?\C6\F5\u0010\u001f\BE\u0002\F15>\ECv\DF\F5\9DD\9B\u0017h{&\E2\B3\u0005\BE\DCw\DD'\F2\u001e#Z\89\EBӈ\8E\"R\EB\DD\FF򕹡@[*\\G\F4\u0007\\\87|\F8+\883DW\u0012-F\FA7\88\u001fA\FC'\A2[q=\u0005\F1\f\A2\u0017E;'Yz]\B5\D0ʯE\u001e'z\8F\E83_\B9\F3\u0011\BF\89\F8\t\A2\E3D]?G\BC\BD\u000f\AB&z\C1\D2\EB\8D#(\BE\9A\E8f\E4\AD&\BA\D8\FA\FAPN\u001a\ECM\u0017\E7\D69\u001c\u001e\A4\CEl\D32Ԫ\82Cg?6vT~l\FAC\FFp]>\F3\9EN\AF\u0001\AE\E6L\85gO\D7\E9\f\F0;\87h\BC\E5\CF:\CDv\B4\B4\u001c\F5@\u0011\ECs_A\F9\EC\FDf\F9\A9\C0{\EF6\F1\E0P\D4\FF\A0\D9\EE\9A2\94?\D7,\EC\E6(\9B\D9\DF\ED\8A\F4\B7f\u0018\EAɚ壨Ǜ@}\F8X\F0\E3Md\BEv\8Ezx\81\C8|\8E\D8J\E3\81\r:\CD\E3\ED\B3'",
       "remedy": "The referenced shell script is invalid. Consider debugging it with the '-n' option on the shell to find and fix the problem."
     },
```
If you open this file you will see it contains shell script and then binary code. The screendump brokes our results json parsing because of binary code.

**Comment by dcantrell** [comment]
I was looking at this one yesterday and noticed the same thing.  The problem is those files report "text/x-shellscript" as the file(1) MIME type.

There are a couple of options I can think of to approach this:

1) Add a config file setting that lets us define wildcard patterns of files to skip the shell syntax check on if we see text/x-shellscript.  For example, the config file could contain something like:

shellsyntax_skip = "*.bin"

And any files that match *.bin and are text/x-shellscript will just be ignored.  This may become difficult to manage going forward.  It does not feel like a real fix.

2) Treat this as a real problem in the package and fix how the archives are stored in the source package.  Why not gzip the bin files?  I'm sure upstream distributes these in formats other than just an executable shell script.

3) file(1) does report "POSIX shell script executable (binary data)" if you look at the standard output and not the MIME type.  The "(binary data)" substring is something librpminspect could key on to see if the file should be skipped since that is causing the syntax validator to fail.

4) For Bourne-compatible shells, explore using ShellCheck if it's available and 'sh -n' returns 2.  I'm not really a fan of this option because ShellCheck is pretty involved and the point of the rpminspect check is to just validate syntax and not do a static analysis.

Of these options, I think #3 is the least bad though I do not really like it either.  Even with ShellCheck, these bin files still generate syntax errors so skipping them may be better if we can't get the packagers to use another source archive format.

Thoughts?

**Comment by ukulekek** [comment]
What do you think about mixing #2 and #3? It can skip the file and report the 'VERIFY' result by pointing to the format problem.

**Comment by dcantrell** [comment]
Combining #2 and #3 could work, but would we need the VERIFY result here?  In the case of the java packages, you would always have to waive the result.  I suppose the error could show up in the packaged script, in which case we should report that.

**Comment by ukulekek** [comment]
Ok, I agree

**Comment by dcantrell** [comment]
Wait, I thought about this some more and the whole thing is an issue with shell scripts in the SRPM.  This check should be ignoring the SRPM because it doesn't matter.  We want to validate things in the built packages.  I can just modify the check to skip content in the SRPM.  Ooops.  :)

**Comment by dcantrell** [comment]
rpminspect -F json -T shellsyntax java-1.8.0-ibm-1.8.0.6.0-2.el8 java-1.8.0-ibm-1.8.0.5.40-3.el8_0
{
   "shell-syntax": [
     {
       "result": "OK",
       "waiver authorization": "Not Waivable"
     }
   ]
 }

Got it working.
