### ISSUE TITLE
Add a test for a dist tag in RPM release of modular packages

### ISSUE THREAD

**Issue by ppisar** [rpminspect/rpminspect#801]
I'd like to add a test for individual modular RPM package like this:

A dist tag stored in an RHEL ≥ 9 RPM Release value must have a resolution finer than RHEL major number.

A motivation is to prevent bugs like <https://bugzilla.redhat.com/show_bug.cgi?id=2094880>.

Example of a bad package:
python3-pyusb-1.0.0-9.module+el8+2554+7a4ca32b.noarch.rpm

Example of a good package:
python3-pyusb-1.0.0-9.module+el8.1.0+4107+4a66eb87.noarch.rpm

Basically  the test should obtain a Release tag "module+el8.1.0+4107+4a66eb87" and check that the "module+el8.1.0+" substring contains dots.

This test should be enabled for RHEL  ≥ 9.
Enforcing this test for RHEL 8 is dubious because it would require all packagers to update packages they never updated. On the other hand, not passing packages are a red flag which packagers should pay special attention to. So maybe reporting them as a failure and require waiving them is not a bad idea.
This test needs to be disabled for Fedora. Fedora does not have Z-streams, thus it does not uses multiple-digit dist tag.

Please do not make the test to specific:
* Do not require exactly 3 numbers. RHEL 10 will probably use only 2 numbers ("el10.0").
* Do not require the dist tag number to match targeted RHEL minor release. E.g. packages for RHEL-9.1.0 can have "el9.0.0". Unchanged packages are reused from older module builds.

**Comment by dcantrell** [comment]
I would like to make this a generic check that can be configured or disabled in the individual vendor data packages for rpminspect.

Is the pattern for RHEL 9 "+module\+el8\.[0-9]+\.[0-9]+\+"?  What I can do is extend the disttag inspection to perform this check on the RPMTAG_RELEASE value but apply a different check depending on the product release (since you say RHEL 10 will likely use a different format).  For product releases not defined in the configuration file, the check can be skipped internally.  This will allow for easy disabling on Fedora.

Thoughts?

**Comment by ppisar** [comment]
Generalizing the test is a good idea.

A regular expression for RHEL 9 is "\.module\+el9\.[0-9]+\.[0-9]+\+". Don't forget that this only apply to modular packages.

**Comment by dcantrell** [comment]
Patch merged.  @ppisar can you send a PR to the internal rpminspect-data package that defines the regular expressions for RHEL?  See the commit for the example block in data/generic.yaml

**Comment by ppisar** [comment]
I created an update for rpminspect-data-redhat.
