### ISSUE TITLE
rpminspect reports a failure on "Apache-2.0 AND (GPL-1.0-or-later OR Artistic-1.0-Perl) AND BSD-3-Clause"

### ISSUE THREAD

**Issue by ppisar** [rpminspect/rpminspect#855]
An rpminspect check for perl-grpc-xs-0.37-5.fc38 <https://artifacts.dev.testing-farm.io/1618b3c3-af80-4e56-9c7d-0e83ff808a4a/> reports a license failure:

~~~~
rpminspect version: 1.11-0.1.202208031929git8204490.fc37 (with data package: 1.10-0.1.202208011434git0eb44e0.fc37)
rpminspect profile: rawhide
new build: perl-grpc-xs-0.37-5.fc38
old build: perl-grpc-xs-0.37-4.fc37 (found in f38-updates koji tag)
[...]
Result: BAD
1) Unapproved license in perl-grpc-xs-0.37-5.fc38.i686: Artistic-1.0-Perl
~~~~

The "GPL-1.0-or-later OR Artistic-1.0-Perl" subexpression is explicitly allowed in licensing guidelines <https://docs.fedoraproject.org/en-US/legal/license-field/#_perl_packages>. This regression is probably triggered by commit bcccdb7493312c1769b9c8e3c1d9f36ada768e91 "Delete disjunctive Artistic-1.0-Perl.toml files" in fedora-license-data.

In that repository there is Artistic-1.0-Perl listed as "not-allowed". I think rpminspect should start evaluating boolean expressions instead of dismissing any occurrence of Artistic-1.0-Perl.

**Comment by dcantrell** [comment]
Yeah, that commit needs to come back.  We were discussing that in the license meetings and if I remember correctly, I prematurely removed that file.

I can't evaluate the boolean expressions in rpminspect.  It seems like you can, but within the vendor's project, they may elect to allow certain license combinations and not others.  So in the case of Artistic-1.0-Perl, we should not have a single entry for it in the license data project but only entries with the compound expression defined since that's what we allow.

I'm going to propose a new file be added to capture this compound expression since we have that in the documentation.

Thanks.

**Comment by dcantrell** [comment]
I've pushed the change to fedora-license-data.
