### ISSUE TITLE
comparison.spec-file-name fails for RHSCL package

### ISSUE THREAD

**Issue by jplesnik** [rpminspect/rpminspect#86]
The test 'dist.rpminspect.comparison.spec-file-name' failed for almost all packages which I built for software collection rh-perl530. For example look at rh-perl530-perl-CPAN-2.27-5.el7 [1]

The spec file is perl-CPAN.spec and the prefix 'rh-perl530-' is added to final rpm.

Error is 
`Spec filename does not match the pattern of NAME.spec; expected 'rh-perl530-perl-CPAN.spec', got 'perl-CPAN.spec'`

Is it possible to ignore the prefix if the macro %scl is defined?

[1] https://dashboard.osci.redhat.com/#/artifact/brew-build/aid/25661682?focus=id:20fdc9d9f7f0-1

**Comment by dcantrell** [comment]
There are a couple of ways to go with this.  First, I could modify the spec-file-name code to handle this special case for %scl.  I am hesitant to do that because it's special case code directly in the inspection that is for the SCL program.  How can handling this be made generic so rpminspect remains adaptable as time goes on.

The easiest thing to do right now is to just exclude the spec-file-name test for SCL packages in rpminspect.  That can be done with "rpminspect -E specname".  That helps when running it locally, but not within gating since you won't have control over the options rpminspect uses.

There is another bug discussing runtime profiles for rpminspect that enable/disable certain tests and change other settings.  I think this can be handled more appropriately once profiles are implemented.  We can configure an SCL rpminspect profile and then gating can invoke rpminspect with the correct profile.

Within the profile, it could set some yet-to-be-determined settings for the spec-file-name check.  Off the top of my head, I am thinking spec-file-name could have a runtime setting that allows the spec file name to test the filename string prefix, entire string, or suffix for a match.  For an SCL runtime profile, rpminspect could just match the string suffix.

Let me know if you have other ideas.

**Comment by dcantrell** [comment]
OK, I've implemented a specname_match setting where you can set it to full, prefix, or suffix.  Running I see that the SCL packages redefine %{name} at build time, so my idea for suffix won't work without some additional steps.  Getting there.

**Comment by dcantrell** [comment]
OK, what I have now is profiles implemented which allow for per-run overrides to rpminspect.conf.  I created an 'scl' profile that overrides the [specname] matching rules.  So here's what it looks like if I run rpminspect as is:

$ rpminspect -T specname rh-perl530-perl-CPAN-2.27-5.el7                                        
spec-file-name:
---------------
1) Spec filename does not exactly match the primary name
rh-perl530-perl-CPAN; got 'perl-CPAN.spec' 
Result: BAD
Waiver Authorization: Anyone

Suggested Remedy: The spec file name does not match the expected
NAME.spec format.  Rename the spec file to conform to this policy.

And now if I run it with the new scl profile:

$ rpminspect -T specname -p scl rh-perl530-perl-CPAN-2.27-5.el7                                                  spec-file-name:
---------------
Result: OK

I'm getting ready to push these changes today.  There will be a new rpminspect as well as a new rpminspect-data-redhat on my internal Copr repo.  My idea with this is that the profiles will give the gating integration the ability to run rpminspect with the right profile depending on the build type.
