### ISSUE TITLE
“Upstream source file changed content” not really informative in many cases

### ISSUE THREAD

**Issue by fweimer-rh** [rpminspect/rpminspect#865]
If the Source: file is a text file directly in dist-git (and not in the lookaside cache), changing it in place (and not with a patch file) is expected. So it's not helpful to flag this.

The question is whether rpminspect can tell whether a file is directly in dist-git or not. If not, maybe suppressing this check for text files is a good idea.

**Comment by dcantrell** [comment]
@fweimer-rh can you give me an NVR of a build that I can use to recreate the issue?

**Comment by msrb** [comment]
@dcantrell The problem was originally reported downstream for `mdadm-4.2-6.el9`.

**Comment by dcantrell** [comment]
I was able to reproduce the issue here.  One thing rpminspect does is determine if the builds you are comparing constitute a rebase or not.  This varies by package, but the prevailing standard is that a package is rebased if the version number changes.  If the name and version number remain the same, but the release numbers change, then rpminspect considers this a maintenance update to the package.  Whether or not you are comparing a rebase build impacts how rpminspect reports findings.

In this case, mdadm's version number remained the same so it does not view the comparison as a rebase.  Then it saw mdadm.rules changed so it reported changed SourceN files at the VERIFY level.  A rebase comparison would ignore that change because it is assumed that a rebased package will have changing sources.  It does not matter whether or not the source file is in the lookaside cache or not because rpminspect is looking at the SRPM.

The easiest way to deal with this is to have rpminspect ignore the mdadm.rules file in the upstream inspection.  In dist-git, create an rpminspect.yaml file with this:

```
---
upstream:
    ignore:
        - mdadm.rules
```

Save that and commit it to dist-git.  The OSCI Gating system will ensure that rpminspect.yaml is the local rpminspect.yaml file used when rpminspect runs on mdadm builds.
