### ISSUE TITLE
Take `%*autosetup` macros into account when looking for corresponding `%patchX` macro

### ISSUE THREAD

**Issue by thozza** [rpminspect/rpminspect#921]
rpminspect generates a VERIFY result such as the following one, when a package has a defined `PatchX:`, but there is no corresponding `%patchX` macro in the `%prep` section. The issue is however reported even when the SPEC file uses the `%autosetup` or `%forgeautosetup` macro, which automatically applies all the defined patches.

It would be great, if rpminspect could check the use of these `%*autosetup` macros and not report the missing `%patchX` in such cases.

This is an example from a RHEL package for osbuild-composer, which uses `%forgeautosetup` macro:
```
patches:
--------

Result: VERIFY
1) Patch number 0 (spec-Fix-ownership-of-the-dnf-json-rpmmd-files.patch) is missing a corresponding %patch0 macro, usually in %prep.
```

## Additional info
https://docs.fedoraproject.org/en-US/packaging-guidelines/#_autosetup

```
rpminspect version: 1.11-0.1.202210201537git704521f.el9 (with data package: 1.7-0.1.202210191719git0f85195.el9)
rpminspect profile: rhel-8
```

**Comment by thozza** [comment]
> Can you tell me what NVR you were giving rpminspect?

`osbuild-composer-62.1-2.el9_1`
`osbuild-composer-62-2.el8_7`

**Comment by dcantrell** [comment]
Thanks.  Yep, definitely see this locally.  So the patches inspection looks for the use of %autosetup or %autopatch but not %forgeautosetup.  Since those macros can be defined by vendors at runtime, I'm moving the list of auto macros that the patches inspection should check for to the config file rather than embedded directly in the inspection.  More flexible that way.
