### ISSUE TITLE
rpminspect return error: Unable to determine product release for 2.fc32 and 1.fc33

### ISSUE THREAD

**Issue by morucci** [rpminspect/rpminspect#98]
Hi David,

It appears that new builds on Koji get the release tag fc33 but rpminspect seems to complain about it: 

```
Unable to determine product release for 2.fc32 and 1.fc33
```
This error is from that job: https://fedora.softwarefactory-project.io/zuul/build/558a681958f6405aac1a3ffc48bbaf6a

Thanks in advance for your help
Fabien

**Comment by dcantrell** [comment]
In cases like this, rpminspect has found a product release for the before build and one for the after build, but they don't match so it doesn't know which one you want to use.  It's expecting the -r option to tell it which product release string to use.

Since this is going to be a recurring thing, one thing I could do is add a setting to the rpminspect.conf file that tells it what rule to go by when deciding which product release string to use.  For example, it could be "favor_product = latest" and in the case of fc32 and fc33, it would take the one that strverscmp()'s as higher than the other.  Or "favor_product = lowest" to always take the lower product release string.  And "favor_product = none" for the current behavior.  What do you think?  It would be easy to implement and would sort of keep this situation from always being a thing.  If I don't do this, then it means on the rpminspect integration side you will need logic to determine if you need to pass -r or not and that seems unnecessary.  Oh, I could also make it so -r always overrides the favor_product setting.

Thoughts?

**Comment by morucci** [comment]
Thanks for the prompt response. Yes if we can avoid adding logic to discover the latest release string at integration level that would be better. So yes a setting such as favor_product in the rpminspect.conf would be perfect. After to be honest I don't understand how this release string influence rpminspect when checking the diff. If you don't mind could you give me a bit of insight about how rpminspect would have behaved if I've passed -r fc32 or -r fc33 in that case ?

Thanks in advance David.
Fabien

**Comment by dcantrell** [comment]
OK, I will get to work on that then.

The product release is necessary because rpminspect uses it to know which data files to open from /usr/share/rpminspect.  For example, in /usr/share/rpminspect/stat-whitelist it would know to open fc32 or fc33 to get the stat(2) whitelist rules.  The data files are split up by release to give us flexibility to change things from release to release.  I decided to use the dist tag value to indicate the release because it was the most convenient.

**Comment by dcantrell** [comment]
The setting is called 'favor_release' and it's under the [vendor] section.  I am setting this to 'newest' in rpminspect-data-fedora.  If it should be something else, let me know.

**Comment by morucci** [comment]
Thanks David. I'll monitor next CI runs and keep you updated.
