### ISSUE TITLE
tests: test_metadata is sensitive to machine hostname

### ISSUE THREAD

**Issue by frozencemetery** [rpminspect/rpminspect#985]
**Describe the bug**
rpminspect-test-suite.test_metadata fails unless the machine hostname matches the approved list (e.g., is localhost) and takes a rather long time to do so.

**To Reproduce**
```
[root@rawhide-efi build]# hostnamectl set-hostname rawhide-efi
[root@rawhide-efi build]# meson test rpminspect-test-suite.test_metadata
ninja: no work to do.
ninja: Entering directory `/root/rpminspect/build'
ninja: no work to do.                                                                                                 [1/1 rpminspect-test-suite.test_metadata        FAIL            62.11s   exit status 1
>>> MALLOC_PERTURB_=153 RPMINSPECT_TEST_DATA_PATH=/root/rpminspect/test/data RPMINSPECT=/root/rpminspect/build/src/rpminspect RPMINSPECT_YAML=/root/rpminspect/data/generic.yaml /usr/bin/python3 -B -m unittest discover -v /root/rpminspect/test test_metadata.py


Ok:                 0   
Expected Fail:      0   
Fail:               1   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   

Full log written to /root/rpminspect/build/meson-logs/testlog.txt
[root@rawhide-efi build]# 
```

**Expected behavior**
```
# hostnamectl set-hostname localhost
# meson test rpminspect-test-suite.test_metadata
ninja: no work to do.
ninja: Entering directory `/root/rpminspect/build'
ninja: no work to do.
1/1 rpminspect-test-suite.test_metadata        OK               5.94s

Ok:                 1   
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   

Full log written to /root/rpminspect/build/meson-logs/testlog.txt
# 
```

**Environment:**
This is git head on Fedora rawhide.

**Comment by frozencemetery** [comment]
It seems like the least work option here is to check the hostname at the start of the tests and skip+warn if they won't pass.  More invasive options could include using something like cwrap to fake hostname/dns.  Templating generic.yaml might work, but I dislike that pattern in general

**Comment by frozencemetery** [comment]
The speed concerns me too - it doesn't make sense that success would be much faster than failure - but I haven't looked into it.

**Comment by dcantrell** [comment]
The long failure time is likely due to socket.getfqdn() in baseclass.py where I try to be somewhat smart about what the buildhost_subdomain should be in the main configuration file.  rpmbuild adds a header tag indicating the build host and one of the checks in rpmdiff and now rpminspect has been to verify that the built RPMs come from "allowed" hosts.

I use socket.getfqdn() to get the FQDN and then lop off the first part and assume the rest is the buildhost_subdomain.  rpmbuild is going to add that in to packages that are built for the test suite.  But if DNS is not configured properly or you've just named a system and there is no DNS set up for that host, .getfqdn() will fail and will take a long time to do so.

rpmbuild does not take forever to time out, so I wonder how it's determining the buildhost in these cases.  What does:

```
rpm -qp --qf "%{buildhost}\n" RPMFILE
```

Say on an RPM built on this host?  Looking at rpm's source, in build/build.c in the buildHost() function I see rpmbuild does a gethostname() and then getaddrinfo() on that if gethostname() succeeded.  If getaddrinfo() succeeds, rpmbuild uses the ai_canonname value.

For the purposes of rpminspect, the check is to ensure the buildhost is on an allowed subdomain.  That is, RHEL packages are built on *.redhat.com hosts.  For the purposes of the test, I think I can speed this up and just use gethostname() and that may involve modifying the test to use strsuffix(), but whatever.

I am curious what it puts in the RPMTAG_BUILDHOST on a system without DNS resolution for the hostname.  I guess it would just be the nodename.
